### ISSUE TITLE
Connection lost with RTL8723BE 

### ISSUE THREAD

**Issue by svenmeier** [lwfinger/rtlwifi_new#22] opened 2015-01-02 18:27 UTC
I'm running Gnome Ubuntu 14.10 with Kernel 3.18 and latest rtlwifi_new.
After 20 to 30 minutes surfing connection is lost to my router and cannot be reestablished. Rebooting the machine sometimes fixes the problem.

Syslog after connection lost:
https://gist.github.com/svenmeier/245bbc5c922c9dd71c4f

**Comment by svenmeier** [comment] 2015-01-02 22:45
Disabling power save solved the issue for me:

http://ubuntuforums.org/showthread.php?p=13119513#post13119513

Is this a known problem with the Realtek driver and is anyone working on it? Or is it just some systems happening, or just accepted as is?

**Comment by svenmeier** [comment] 2015-01-03 15:52
Syslog with debug=1 when driver tries to reconnect:

https://gist.github.com/svenmeier/a7c6924e23e97f9ce055

**Comment by sunny0** [comment] 2015-01-06 02:08
I've

options rtl8723be fwlps=0 swlps=0

seems to work well enough for now

**Comment by svenmeier** [comment] 2015-01-06 18:24
I'm already using these options. Still reliability is far from "works well enough":
- yesterday connection to Netgear WNDR3700 dropped after half an hour 
- suprisingle a connection to Fritzbox 7390 stayed stable for almost 2 hours afterwards
- today connection dropped almost immediately after starting the notebook

Reloading the module does not help, turning off wifi and turning it on again will never successfully reestablish a connection :(.

I'm wondering what the driver is doing on reconnect, see the syslog attached above. Shouldn't there be an indication of the problem, an error message or something?

**Comment by lwfinger** [comment] 2015-01-06 18:58
I am currently using this driver loaded with "ips=0". It is connected to a Trendnet AC1750 access point. The connection was made almost 15 hours ago, and has only lost the connection once. It recovered that time without any manual intervention.

**Comment by svenmeier** [comment] 2015-01-06 20:00
Just noticed the following event log with "iw event":

When still connected a scan is performed regularily approx. every 5 minutes:
wlan0 (phy #0): scan started
wlan0 (phy #0): scan finished: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472, ""

After 20 minutes something is happening:

wlan0: del station 9c:c7:a6:0a:28:93
wlan0 (phy #0): disassoc 9c:c7:a6:0a:28:93 -> 10:08:b1:3e:47:01 reason 2: Previous authentication no longer valid
wlan0 (phy #0): disconnected (by AP) reason: 2: Previous authentication no longer valid
phy #0: regulatory domain change: set to world roaming by the wireless core upon initialization request
wlan0 (phy #0): scan started
wlan0 (phy #0): scan finished: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472, "MyNetwork" ""
wlan0: new station 9c:c7:a6:0a:28:93
wlan0: del station 9c:c7:a6:0a:28:93
wlan0 (phy #0): auth: timed out
wlan0 (phy #0): scan started
wlan0 (phy #0): scan finished: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472, "Gattaca" ""
wlan0 (phy #0): scan started
wlan0 (phy #0): scan finished: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472, "Gattaca" ""
wlan0: new station 9c:c7:a6:0a:28:93
wlan0 (phy #0): auth 9c:c7:a6:0a:28:93 -> 10:08:b1:3e:47:01 status: 0: Successful
wlan0 (phy #0): assoc 9c:c7:a6:0a:28:93 -> 10:08:b1:3e:47:01 status: 0: Successful
wlan0 (phy #0): connected to 9c:c7:a6:0a:28:93
phy #0: regulatory domain change: set to DE by a country IE request on phy0

Is this something to be expected? After this sequence of events the connection is no longer working. Syslog is filled with a huge amount of entries though.

**Comment by Vourhey** [comment] 2015-01-07 19:54
I'm using Linux Mint 17.1 with kernel 3.16 and I have the same problem. After the connection was lost I can't get it back. Only rebooting the machine helps.
I also see it 
iw event 
wlan0 (phy #0): scan started
wlan0 (phy #0): scan finished: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472, "AZAZA_86" ""
wlan0: new station ac:f1:df:c8:fb:b3
wlan0: del station ac:f1:df:c8:fb:b3
wlan0 (phy #0): auth: timed out
wlan0 (phy #0): scan started
wlan0 (phy #0): scan finished: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472, "AZAZA_86" ""
wlan0 (phy #0): scan started
wlan0 (phy #0): scan finished: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472, ""
wlan0: new station ac:f1:df:c8:fb:b3
wlan0: del station ac:f1:df:c8:fb:b3
wlan0 (phy #0): auth: timed out

**Comment by troy-tan** [comment] 2015-01-08 01:12
"Previous authentication no longer valid" maybe the keypoint, the problem is to figure out what makes AP
disconnect the STA.

**Comment by akashpal21** [comment] 2015-01-08 07:41
The driver(rtlwifi_new) along with "options rtl8723be fwlps=N ips=N" and kernel 3.16 seems to work fine with me. Connection drop was a issue in kernel 3.13, but it seems to have been solved in kernel 3.16.

**Comment by svenmeier** [comment] 2015-01-08 23:12
I'm tried "options rtl8723be fwlps=0 ips=0" already (AFAIK 0 and N can be used interchangeably), but this didn't help.

Just tried again with Kernel 3.18 and the system reached an instable connection soon after:

$ sudo iwlist scan
wlan0     Failed to read scan data : Resource temporarily unavailable
lo        Interface doesn't support scanning.
$ rfkill list
0: ideapad_wlan: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: ideapad_bluetooth: Bluetooth
	Soft blocked: no
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
3: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no

**Comment by lwfinger** [comment] 2015-01-09 19:48
Such a scan failure will occur is NetworkManager is running and is doing a scan at that moment. The same thing probably happens with wicd, and may happen with wpa_supplicant. In any case, if you wait for a few seconds, does the scan request work?

**Comment by svenmeier** [comment] 2015-01-11 22:04
I've done a little more testing on this weekend:
Indeed, the scan works again *even* if the connection cannot be re-established.

It would be interesting what the driver/card is doing after connection failure:

https://gist.github.com/svenmeier/2d6e60745bd53b6a7345

What can I do to get more information about the connection failure?

    "<warn> Activation (wlan0) failed for connection 'MyNetwork'"

I'm a programmer, so I could debug or work with the source code. But I need a little guidance for this - kernel modules are not my field of experience.

**Comment by svenmeier** [comment] 2015-01-11 22:33
BTW I blacklisted ideapad-laptop because it was reported to have troubles with hard blocking wifi in 3.16, but this didn't help either.

Power management should not be the cause of the problem:
sandra@MyComputer:~$ iwconfig
wlan0     IEEE 802.11bgn  ESSID:"MyNetwork"  
          Mode:Managed  Frequency:2.412 GHz  Access Point: 9C:C7:A6:0A:28:93   
          Bit Rate=150 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:off
          Link Quality=56/70  Signal level=-54 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:205   Missed beacon:0
lo        no wireless extensions.
sandra@MyComputer:~$ more /sys/module/rtl8723be/parameters/ips 
N
sandra@MyComputer:~$ more /sys/module/rtl8723be/parameters/fwlps
N

**Comment by svenmeier** [comment] 2015-01-14 17:33
Yesterday wifi worked fine for over two hours. Resumed this morning and wifi dropped after a few minutes.

dmesg shows the scan-"auth: timed out" loop:

    wlan0: new station 9c:c7:a6:0a:28:93
    wlan0: del station 9c:c7:a6:0a:28:93
    wlan0 (phy #0): auth: timed out
    wlan0 (phy #0): scan started

Is my notebook suffering from amnesia?

**Comment by svenmeier** [comment] 2015-01-16 21:30
I've continued my investigations without network manager.

It seems configuring the wpa_supplicant with CCMP explicitely improved the situation:

network={
	ssid="...."
	group=CCMP
	pairwise=CCMP
	psk=...
}

No connection drops for over three hours - that's a record ;).
Authentication still seems to struggle from time to time though, but the connection recovers after a few seconds stuttering.

The following non-recoverable disconnect generated:
wlan0: New scan results available (own=0 ext=0)
wlan0: Radio work 'scan'@0x1267cd0 done in 0.830758 seconds
wlan0: Selecting BSS from priority group 0
wlan0: 0: c0:25:06:ea:4c:8a ssid='Gattaca' wpa_ie_len=0 rsn_ie_len=20 caps=0x11 level=-38
wlan0:    skip - disabled temporarily for 8 second(s)
wlan0: 1: 04:a1:51:7e:d7:1f ssid='DownGattaca' wpa_ie_len=0 rsn_ie_len=20 caps=0x11 level=-54
wlan0:    skip - disabled temporarily for 8 second(s)
wlan0: No suitable network found
wlan0: Setting scan request: 5.000000 sec
wlan0: Starting AP scan for wildcard SSID
wlan0: Determining shared radio frequencies (max len 1)
wlan0: Shared frequencies (len=0): completed iteration
wlan0: Add radio work 'scan'@0x1267cd0
wlan0: First radio work item in the queue - schedule start immediately
wlan0: Starting radio work 'scan'@0x1267cd0 after 0.000025 second wait
Scan requested (ret=0) - scan timeout 30 seconds
RTM_NEWLINK: operstate=0 ifi_flags=0x1003 ([UP])
RTM_NEWLINK, IFLA_IFNAME: Interface 'wlan0' added
WEXT: if_removed already cleared - ignore event
Wireless event: cmd=0x8b19 len=16
wlan0: Event SCAN_RESULTS (3) received
Received 1004 bytes of scan results (2 BSSes)
wlan0: BSS: Start scan result update 29
BSS: last_scan_res_used=2/32
wlan0: New scan results available (own=0 ext=0)
wlan0: Radio work 'scan'@0x1267cd0 done in 0.831458 seconds
wlan0: Selecting BSS from priority group 0
wlan0: 0: c0:25:06:ea:4c:8a ssid='Gattaca' wpa_ie_len=0 rsn_ie_len=20 caps=0x11 level=-38
wlan0:    skip - disabled temporarily for 2 second(s)
wlan0: 1: 04:a1:51:7e:d7:1f ssid='DownGattaca' wpa_ie_len=0 rsn_ie_len=20 caps=0x11 level=-54
wlan0:    skip - disabled temporarily for 2 second(s)
wlan0: No suitable network found
wlan0: Setting scan request: 5.000000 sec
wlan0: Starting AP scan for wildcard SSID
wlan0: Determining shared radio frequencies (max len 1)
wlan0: Shared frequencies (len=0): completed iteration
wlan0: Add radio work 'scan'@0x1267cd0
wlan0: First radio work item in the queue - schedule start immediately
wlan0: Starting radio work 'scan'@0x1267cd0 after 0.000036 second wait
Scan requested (ret=0) - scan timeout 30 seconds
RTM_NEWLINK: operstate=0 ifi_flags=0x1003 ([UP])
RTM_NEWLINK, IFLA_IFNAME: Interface 'wlan0' added
WEXT: if_removed already cleared - ignore event
Wireless event: cmd=0x8b19 len=16
wlan0: Event SCAN_RESULTS (3) received
Received 1004 bytes of scan results (2 BSSes)
wlan0: BSS: Start scan result update 30
BSS: last_scan_res_used=2/32
wlan0: New scan results available (own=0 ext=0)
wlan0: Radio work 'scan'@0x1267cd0 done in 0.834451 seconds
wlan0: Selecting BSS from priority group 0
wlan0: 0: c0:25:06:ea:4c:8a ssid='Gattaca' wpa_ie_len=0 rsn_ie_len=20 caps=0x11 level=-42
wlan0: CTRL-EVENT-SSID-REENABLED id=0 ssid="Gattaca"
wlan0:    selected based on RSN IE
wlan0:    selected BSS c0:25:06:ea:4c:8a ssid='Gattaca'
wlan0: Considering connect request: reassociate: 1  selected: c0:25:06:ea:4c:8a  bssid: 00:00:00:00:00:00  pending: 00:00:00:00:00:00  wpa_state: SCANNING  ssid=0x124af30  current_ssid=(nil)
wlan0: Request association with c0:25:06:ea:4c:8a
wlan0: Add radio work 'connect'@0x1266da0
wlan0: First radio work item in the queue - schedule start immediately
wlan0: Starting radio work 'connect'@0x1266da0 after 0.000013 second wait
wlan0: Trying to associate with c0:25:06:ea:4c:8a (SSID='Gattaca' freq=2412 MHz)
FT: Stored MDIE and FTIE from (Re)Association Response - hexdump(len=0):
wlan0: Cancelling scan request
wlan0: WPA: clearing own WPA/RSN IE
wlan0: Automatic auth_alg selection: 0x1
RSN: PMKSA cache search - network_ctx=0x124af30 try_opportunistic=0
RSN: Search for BSSID c0:25:06:ea:4c:8a
RSN: No PMKSA cache entry found
wlan0: RSN: using IEEE 802.11i/D9.0
wlan0: WPA: Selected cipher suites: group 16 pairwise 16 key_mgmt 2 proto 2
wlan0: WPA: Selected mgmt group cipher 32
wlan0: WPA: clearing AP WPA IE
WPA: set AP RSN IE - hexdump(len=22): 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00
wlan0: WPA: using GTK CCMP
wlan0: WPA: using PTK CCMP
wlan0: WPA: using KEY_MGMT WPA-PSK
wlan0: WPA: not using MGMT group cipher
WPA: Set own WPA IE default - hexdump(len=22): 30 14 01 00 00 0f ac 04 01 00 00 0f ac 04 01 00 00 0f ac 02 00 00
wlan0: State: SCANNING -> ASSOCIATING
wpa_driver_wext_set_operstate: operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
Limit connection to BSSID c0:25:06:ea:4c:8a freq=2412 MHz based on scan results (bssid_set=0)
wpa_driver_wext_associate
wpa_driver_wext_set_drop_unencrypted
wpa_driver_wext_set_psk
ioctl[SIOCSIWFREQ]: Device or resource busy
wlan0: Association request to the driver failed
wlan0: Setting authentication timeout: 5 sec 0 usec
EAPOL: External notification - EAP success=0
EAPOL: External notification - EAP fail=0
EAPOL: External notification - portControl=Auto
RTM_NEWLINK: operstate=0 ifi_flags=0x1003 ([UP])
RTM_NEWLINK, IFLA_IFNAME: Interface 'wlan0' added
WEXT: if_removed already cleared - ignore event
Wireless event: cmd=0x8b1a len=16
RTM_NEWLINK: operstate=0 ifi_flags=0x1003 ([UP])
RTM_NEWLINK, IFLA_IFNAME: Interface 'wlan0' added
WEXT: if_removed already cleared - ignore event
Wireless event: cmd=0x8b06 len=12
RTM_NEWLINK: operstate=0 ifi_flags=0x1003 ([UP])
RTM_NEWLINK, IFLA_IFNAME: Interface 'wlan0' added
WEXT: if_removed already cleared - ignore event
Wireless event: cmd=0x8b1a len=23
wlan0: Authentication with c0:25:06:ea:4c:8a timed out.
Added BSSID c0:25:06:ea:4c:8a into blacklist
wlan0: Request to deauthenticate - bssid=00:00:00:00:00:00 pending_bssid=c0:25:06:ea:4c:8a reason=3 state=ASSOCIATING
wpa_driver_wext_deauthenticate
wlan0: Event DEAUTH (12) received
wlan0: Deauthentication notification
wlan0:  * reason 3 (locally generated)
Deauthentication frame IE(s) - hexdump(len=0): [NULL]
wlan0: CTRL-EVENT-DISCONNECTED bssid=c0:25:06:ea:4c:8a reason=3 locally_generated=1
wlan0: Auto connect enabled: try to reconnect (wps=0 wpa_state=5)
wlan0: Setting scan request: 0.100000 sec
wlan0: Radio work 'connect'@0x1266da0 done in 5.044005 seconds
BSSID c0:25:06:ea:4c:8a blacklist count incremented to 2
Continuous association failures - consider temporary network disabling
wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="Gattaca" auth_failures=5 duration=20
wlan0: Blacklist count 13 --> request scan in 10000 ms
wlan0: Ignore new scan request for 10.000000 sec since an earlier request is scheduled to trigger sooner
wlan0: Disconnect event - remove keys
wlan0: State: ASSOCIATING -> DISCONNECTED
wpa_driver_wext_set_operstate: operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
EAPOL: External notification - portEnabled=0
EAPOL: External notification - portValid=0
EAPOL: External notification - EAP success=0
wlan0: State: DISCONNECTED -> DISCONNECTED
wpa_driver_wext_set_operstate: operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
EAPOL: External notification - portEnabled=0
EAPOL: External notification - portValid=0
wlan0: Ignore new scan request for 1.000000 sec since an earlier request is scheduled to trigger sooner
RTM_NEWLINK: operstate=0 ifi_flags=0x1003 ([UP])
RTM_NEWLINK, IFLA_IFNAME: Interface 'wlan0' added
WEXT: if_removed already cleared - ignore event
Wireless event: cmd=0x8b1a len=16
wlan0: State: DISCONNECTED -> SCANNING
wlan0: Starting AP scan for wildcard SSID
wlan0: Add radio work 'scan'@0x1267cd0
wlan0: First radio work item in the queue - schedule start immediately
wlan0: Starting radio work 'scan'@0x1267cd0 after 0.000019 second wait
Scan requested (ret=0) - scan timeout 30 seconds
RTM_NEWLINK: operstate=0 ifi_flags=0x1003 ([UP])
RTM_NEWLINK, IFLA_IFNAME: Interface 'wlan0' added
WEXT: if_removed already cleared - ignore event
Wireless event: cmd=0x8b19 len=16
wlan0: Event SCAN_RESULTS (3) received
Received 496 bytes of scan results (1 BSSes)
wlan0: BSS: Start scan result update 31
BSS: last_scan_res_used=1/32
wlan0: New scan results available (own=0 ext=0)
wlan0: Radio work 'scan'@0x1267cd0 done in 0.831617 seconds
wlan0: Selecting BSS from priority group 0
wlan0: 0: c0:25:06:ea:4c:8a ssid='Gattaca' wpa_ie_len=0 rsn_ie_len=20 caps=0x11 level=-50
wlan0:    skip - blacklisted (count=2 limit=0)
wlan0: No APs found - clear blacklist and try again
Removed BSSID c0:25:06:ea:4c:8a from blacklist (clear)
wlan0: Selecting BSS from priority group 0
wlan0: 0: c0:25:06:ea:4c:8a ssid='Gattaca' wpa_ie_len=0 rsn_ie_len=20 caps=0x11 level=-50
wlan0:    skip - disabled temporarily for 19 second(s)
wlan0: No suitable network found
wlan0: Setting scan request: 5.000000 sec
^Cwlan0: Removing interface wlan0
wlan0: Request to deauthenticate - bssid=00:00:00:00:00:00 pending_bssid=00:00:00:00:00:00 reason=3 state=SCANNING
wlan0: State: SCANNING -> DISCONNECTED
wpa_driver_wext_set_operstate: operstate 0->0 (DORMANT)
netlink: Operstate: ifindex=2 linkmode=-1 (no change), operstate=5 (IF_OPER_DORMANT)
EAPOL: External notification - portEnabled=0
EAPOL: External notification - portValid=0
wpa_driver_wext_set_countermeasures
wlan0: BSS: Remove id 6 BSSID 04:a1:51:7e:d7:1f SSID 'DownGattaca' due to wpa_bss_flush
wlan0: BSS: Remove id 5 BSSID c0:25:06:ea:4c:8a SSID 'Gattaca' due to wpa_bss_flush
wlan0: Cancelling scan request
wlan0: Cancelling authentication timeout
Remove interface wlan0 from radio phy0
Remove radio phy0
netlink: Operstate: ifindex=2 linkmode=0 (kernel-control), operstate=6 (IF_OPER_UP)
wlan0: CTRL-EVENT-TERMINATING 

At least now I can just restart wpa_supplicant and don't have to reboot.

**Comment by svenmeier** [comment] 2015-01-16 21:33
Is it normal to see a group rekeying every other 10 minutes?

wlan0: RX EAPOL from c0:25:06:ea:4c:8a
RX EAPOL - hexdump(len=131): 02 03 00 7f 02 13 82 00 10 00 00 00 00 00 00 00 03 10 51 c4 46 66 69 5e 36 6c d5 a4 c1 3a 12 68 48 7e 78 8d 63 ea 04 e3 50 9e da 75 04 34 07 8f 22 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 30 c8 35 28 58 84 ce 9f ca 49 a8 0e cd 36 b2 c5 00 20 ad 68 f6 22 49 0d cc fe 53 81 4c 10 3b ad 88 f7 81 94 f9 ed c1 22 4f e6 2c 76 02 96 5e 42 d7 88
wlan0: IEEE 802.1X RX: version=2 type=3 length=127
wlan0:   EAPOL-Key type=2
wlan0:   key_info 0x1382 (ver=2 keyidx=0 rsvd=0 Group Ack MIC Secure Encr)
wlan0:   key_length=16 key_data_length=32
  replay_counter - hexdump(len=8): 00 00 00 00 00 00 00 03
  key_nonce - hexdump(len=32): 10 51 c4 46 66 69 5e 36 6c d5 a4 c1 3a 12 68 48 7e 78 8d 63 ea 04 e3 50 9e da 75 04 34 07 8f 22
  key_iv - hexdump(len=16): 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  key_rsc - hexdump(len=8): 00 00 00 00 00 00 00 00
  key_id (reserved) - hexdump(len=8): 00 00 00 00 00 00 00 00
  key_mic - hexdump(len=16): 30 c8 35 28 58 84 ce 9f ca 49 a8 0e cd 36 b2 c5
WPA: RX EAPOL-Key - hexdump(len=131): 02 03 00 7f 02 13 82 00 10 00 00 00 00 00 00 00 03 10 51 c4 46 66 69 5e 36 6c d5 a4 c1 3a 12 68 48 7e 78 8d 63 ea 04 e3 50 9e da 75 04 34 07 8f 22 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 30 c8 35 28 58 84 ce 9f ca 49 a8 0e cd 36 b2 c5 00 20 ad 68 f6 22 49 0d cc fe 53 81 4c 10 3b ad 88 f7 81 94 f9 ed c1 22 4f e6 2c 76 02 96 5e 42 d7 88
RSN: encrypted key data - hexdump(len=32): ad 68 f6 22 49 0d cc fe 53 81 4c 10 3b ad 88 f7 81 94 f9 ed c1 22 4f e6 2c 76 02 96 5e 42 d7 88
WPA: decrypted EAPOL-Key key data - hexdump(len=24): [REMOVED]
wlan0: WPA: RX message 1 of Group Key Handshake from c0:25:06:ea:4c:8a (ver=2)
RSN: msg 1/2 key data - hexdump(len=24): dd 16 00 0f ac 01 01 00 8c 8a 9c b5 40 0f 7d b2 c8 28 5f 73 da 10 81 8f
WPA: GTK in EAPOL-Key - hexdump(len=24): [REMOVED]
RSN: received GTK in group key handshake - hexdump(len=18): 01 00 8c 8a 9c b5 40 0f 7d b2 c8 28 5f 73 da 10 81 8f
wlan0: State: COMPLETED -> GROUP_HANDSHAKE
WPA: Group Key - hexdump(len=16): [REMOVED]
wlan0: WPA: Installing GTK to the driver (keyidx=1 tx=0 len=16)
WPA: RSC - hexdump(len=6): 00 00 00 00 00 00
wpa_driver_wext_set_key: alg=3 key_idx=1 set_tx=0 seq_len=6 key_len=16
wlan0: WPA: Sending EAPOL-Key 2/2
WPA: KCK - hexdump(len=16): [REMOVED]
WPA: Derived Key MIC - hexdump(len=16): d2 ee 8b b6 d4 ad 4d 28 38 62 67 d5 46 ee 79 a4
WPA: TX EAPOL-Key - hexdump(len=99): 01 03 00 5f 02 03 02 00 00 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 d2 ee 8b b6 d4 ad 4d 28 38 62 67 d5 46 ee 79 a4 00 00
wlan0: WPA: Group rekeying completed with c0:25:06:ea:4c:8a [GTK=CCMP]
wlan0: Cancelling authentication timeout
wlan0: State: GROUP_HANDSHAKE -> COMPLETED

**Comment by svenmeier** [comment] 2015-01-16 21:34
Just seen these lines in rtl_wifi's output:

Jan 16 22:31:35 SandraOrange kernel: [10140.353082] rtlwifi:rtl_op_set_key():<0-0> not open hw encryption
Jan 16 22:31:35 SandraOrange kernel: [10140.353153] rtlwifi:rtl_is_special_data():<200-1> 802.1X Tx EAPOL pkt!!

Is this normal?

**Comment by svenmeier** [comment] 2015-01-16 21:43
And some more "unusual"(?) output:

Jan 16 22:39:39 SandraOrange kernel: [10624.802515] rtlwifi:rtl_watchdog_wq_callback():<0-0> AP off for 4 s

**Comment by svenmeier** [comment] 2015-01-17 08:23
Do log lines with exclamation marks mark something special?

Jan 17 09:18:35 SandraOrange kernel: [16053.770210] rtl8723be:rtl8723be_dm_check_txpower_tracking():<0-0> Trigger 8723be Thermal Meter!!
.........
Jan 17 09:18:37 SandraOrange kernel: [16055.772055] rtl8723be:rtl8723be_dm_check_txpower_tracking():<0-0> Schedule TxPowerTracking !!

**Comment by svenmeier** [comment] 2015-01-17 08:28
MinUndecoratedPWDBForDM seems to be counting up all the time:

Jan 17 09:23:35 SandraOrange kernel: [16354.495585] rtl8723be:rtl8723be_dm_find_minimum_rssi():<0-0> MinUndecoratedPWDBForDM =38

**Comment by lwfinger** [comment] 2015-01-17 21:00
Remember that only Realtek knows what the chip is doing on the inside. I have no idea what parameter MinUndecoratedPWDBForDM does.

Group rekeying is part of TKIP. It greatly enhances security because by the time an intruder might find a decryption key, it will have changed. Mine is usually set at 3600 min - 20 minutes is a bit shorter than usual, but that is a parameter of the AP, not the station.

**Comment by svenmeier** [comment] 2015-01-18 13:19
I've found a workaround for my system:

sandra@SandraOrange:~$ more /etc/modprobe.d/rtl8723be.conf
options rtl8723be fwlps=N swlps=N swenc=Y **disable_watchdog=Y**

I've already followed instructions to turn off power saving (fwlps & swlps) and moving the burden of encryption from the wifi card (swenc). But scanning through all log output of wpa_supplicant and system, I noticed that the watchdog seems to put much strain on the wifi card too.

Since disabling the watchdog I can enjoy a fast and rock solid connection to the ap!

I wouldn't close this issue until we have identified the root cause of this problem. Hopefully others can confirm my findings.

**Comment by svenmeier** [comment] 2015-01-19 22:28
Today I've:
- installed Ubuntu 14.10 from scratch -> connections dropped
- installed latest driver from rtlwifi_new -> connections dropped
- added module parameters as in previous comment -> good connection
- updated Ubuntu which overwrote the rtl8723be driver -> connections dropped
- reinstalled rtlwifi_new -> good connections

Still wpa_supplicant keeps "group rekeying" every 10 minutes, causing 5 to 10 seconds pause on the wifi connection.

**Comment by lwfinger** [comment] 2015-01-19 22:45
The group rekey interval is set by the AP, not the driver. If you cannot change the parameters in the AP, then you will need to live with that.

**Comment by sunny0** [comment] 2015-01-20 18:48
It's pretty frustrating having drivers that don't work, or only sort of work... i know. Maybe you could try blacklisting btusb and/or btcoexist. I only suggest this because it has solved (...) my wifi connection issues. Of course, now i don't have bluetooth, but it's better than having unreliable wifi.

**Comment by JohannesBuchner** [comment] 2015-06-12 18:20
I have had similar issues (pings give sendmsg: No buffer space available or icmp_seq=42 Destination Host Unreachable or just generally no traffic throughput). (I am on Gentoo, kernel 3.18.12, using rtl8723be)

I could always reset the driver via::

```
systemctl stop NetworkManager
for m in rtl8723be btcoexist rtl_pci rtlwifi
do 
	rmmod $m
	sleep 0.1
done
modprobe rtl8723be
systemctl start NetworkManager
```
Today I upgraded from 3498e57 to 31b961f and re-installed the driver. So far no problem. Will keep you up to date if it holds...

Thank you for your work on rtlwifi!

**Comment by lwfinger** [comment] 2015-06-12 18:31
Whenever you have problems, it is always advisable to do a new pull on the git repo. If you are downloading the zipped version, then it is a lot of trouble. For that reason, I recommend that you always do a 'git clone' when you start. That way updates are trivial - 'git pull'.

**Comment by JohannesBuchner** [comment] 2015-06-20 15:29
Reporting back: the driver has worked for me without issues (as client to various APs, I do not use  Bluetooth).

**Comment by geromek** [comment] 2015-11-15 15:24
What worked for me was enabling the MSI parameter [message signal interupt ]. I have a lenovo Z50 laptop. My wifi would work with all wifi laptop manufacturers but i was having a problem with a Lancorm wifi router at a Hotel I once stayed.

what i did was this. I scrowled to the file "sw.c" in the folder
 
"/home/peter/rtlwifi_new/rtl8723be"

Then in the sw.c file, I initiated the variable "msi_support" to "false" under the data type "rtl_mod_params rtl8723be_mod_params" i.e

static struct rtl_mod_params rtl8723be_mod_params = {
	.sw_crypto = false,
	.inactiveps = true,
	.swctrl_lps = false,
	.fwctrl_lps = true,
	.msi_support = false,
};

Since msi_support is by default disabled, we have to appropriately initialize it as disabled,

I then complied the code, ie

cd rtl8723be
make clean
sudo make install
sudo modprobe rtl8723be 

after that I set the msi parameter to 1, in the file "rtl8723be.conf" which can be found under 
"/etc/modprobe.d"
i.e
options rtl8723be fwlps=N ips=N swenc=Y msi=1

You may have to reboot the computer and wait after a couple of minutes after restarting the browser for the msi to be triggered.

This worked for a lenovo z50. Depending on your pc, you may toggle and choose instead an msi of 0

**Comment by lwfinger** [comment] 2015-11-15 16:59
By now I'm sure that you know about the "modinfo" command and that it lists all the module parameters, and their default values. I have no idea why one connecting to a particular AP could be affected by the interrupt method, but I do know that Lenovo boxes sometimes have strange interfacing.

**Comment by lwfinger** [comment] 2016-12-02 20:24
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Closed by lwfinger** 2016-12-02 20:24 UTC
