### ISSUE TITLE
rtl8192ce:rtl92ce_get_hw_reg [rtl8192ce]:<0-0> switch case not processed

### ISSUE THREAD

**Issue by jshand2015** [lwfinger/rtlwifi_new#156] opened 2016-10-19 08:08 UTC
i am concerned to know if this is a bug?  i use the rtl8192ce driver

**Comment by lwfinger** [comment] 2016-10-19 13:46
No. It is not a bug. The call is for a function that is not needed in rtl8192ce.

**Comment by lwfinger** [comment] 2016-12-02 19:59
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Closed by lwfinger** 2016-12-02 19:59 UTC
