### ISSUE TITLE
rtl8821ae connection drop outs.

### ISSUE THREAD

**Issue by morguldir** [lwfinger/rtlwifi_new#323] opened 2018-02-11 00:20 UTC
Duplicate of all the others, kernel 4.15.1 and 4.15.2 breaks it from what i can see, it breaks it with the drivers here and the ones in the 4.15.* kernel. It seems to be occur less than it did before though. You might have to run multiple hours of downloading for it to trigger.

**Comment by Criminalllz** [comment] 2018-02-11 16:37
Okay, here is the info i have for now:
4.15.2 included rtlwifi is back to how it was after the alignment issues fix
4.15.2 with rtlwifi_new is back to how it was after the alignment issues fix
4.15.2 with rtlwifi_new with https://github.com/lwfinger/rtlwifi_new/commit/9046f6f4c7d5de4580ef49605ec7209125437499 reverted is very slightly more unstable than 4.14 was.

**Comment by lwfinger** [comment] 2018-02-11 17:51
Version 4.15.2 does not have the latest fix for the alignment issue. None of the mainline kernel versions have that change. It has been accepted into wireless-drivers and is working its way through the process. When it is accepted into 4.16, it will be backported to 4.15.x and 4.14.x.

Commit 9046f6 is found in the master branch. That branch is essentially abandoned. If you want the latest code, you should be running the extended branch. Even the mainline kernel drivers are better than master.

I am surprised that changing the L1 latency does not fix your system. My laptop, and those of the people that bisected the problem, were fixed by the the equivalent of commit 0342da64608e in the extended branch. Note that it is not possible to leave the original 16-bit (unaligned) read in place. It crashes every ARM system.

**Comment by alexeymuranov** [comment] 2018-02-12 16:19
@lwfinger, the README in master does not mention that for rtl8821ae the `extended` branch is more appropriate.  Do i understand correctly that `extended` branch should be used for rtl8821ae?  Do you keep any up to date installation instructions somewhere by any chance?  Thanks.

**Comment by Jakecheslekov** [comment] 2018-02-17 02:06
I'm also having issues with rtl8821ae, but my connection doesn't drop out - whenever I try to disconnect from a WiFi network or connect to another network, it just crashes networkmanager & I have to restart the networkmanager. I'm trying to play around with the settings in the hopes that I find the 'sweet 'spot'.

**Comment by lwfinger** [comment] 2018-02-17 02:28
The problems with disconnection or connecting to another network happen only for some distros. For example, on any version of openSUSE, those operations have no problems. It seems that the problem is in your user-code stuff - probably NetworkManager.

I have no idea what distro you use, but Ubuntu seems to be most affected.

**Closed** 2020-07-06 19:49 UTC
