### ISSUE TITLE
Error efuse.o

### ISSUE THREAD

**Issue by blackw0lf9** [lwfinger/rtlwifi_new#576] opened 2020-05-08 13:10 UTC
Hello,
When I try to do "make" it appears the following error:

CC [M]  /root/rtlwifi_new/efuse.o
/root/rtlwifi_new/efuse.c: In function ‘rtw_read8_physical_efuse’:
/root/rtlwifi_new/efuse.c:133:8: error: implicit declaration of function ‘read_poll_timeout’; did you mean ‘readb_poll_timeout’? [-Werror=implicit-function-declaration]
  133 |  ret = read_poll_timeout(rtw_read32, efuse_ctl, efuse_ctl & BIT_EF_FLAG,
      |        ^~~~~~~~~~~~~~~~~
      |        readb_poll_timeout
/root/rtlwifi_new/efuse.c:133:8: warning: ‘efuse_ctl’ is used uninitialized in this function [-Wuninitialized]
  133 |  ret = read_poll_timeout(rtw_read32, efuse_ctl, efuse_ctl & BIT_EF_FLAG,
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  134 |     1000, 100000, false, rtwdev, REG_EFUSE_CTRL);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.5.0-kali2-common/scripts/Makefile.build:271: /root/rtlwifi_new/efuse.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:1707: /root/rtlwifi_new] Error 2
make[1]: *** [/usr/src/linux-headers-5.5.0-kali2-common/Makefile:179: sub-make] Error 2
make[1]: se sale del directorio '/usr/src/linux-headers-5.5.0-kali2-amd64'
make: *** [Makefile:52: all] Error 2

Please could someone help me? Thanks in advance.

Regards

**Comment by lwfinger** [comment] 2020-05-08 15:18
I just pushed a fix for this problem. Sorry for any inconvenience. Do a 'git pull' and it should work.

**Comment by blackw0lf9** [comment] 2020-05-08 22:24
It works correctly! Thank you so much for your quick response and solution! Best regards

**Comment by denniskoster** [comment] 2020-05-13 09:30
I am having this issue on the `rtw88` branch. Has the fix also been deployed there?

**Comment by lwfinger** [comment] 2020-05-13 15:45
If you actually do a 'git pull' on the rtw88 branch, you will find that the code has been COMPLETELY changed. No old errors can possibly still be active!!

**Comment by denniskoster** [comment] 2020-05-13 16:09
Well, I did a fresh clone this morning. When you look at the actual code clearly something went wrong; https://github.com/lwfinger/rtlwifi_new/blob/rtw88/efuse.c#L133

I think the changes made were reverted by `0f953687dddac7a9f6c0d82fc7e2c5209ed1fcd9`: https://github.com/lwfinger/rtlwifi_new/commit/0f953687dddac7a9f6c0d82fc7e2c5209ed1fcd9#diff-0629a7cbe2719f8ed029bdbe8d2b4cb5

**Comment by lwfinger** [comment] 2020-05-13 16:51
Sorry for the confusion. I am running kernel 5.7-rc5 where those macros are built in and I missed read_poll_timeout(). Do another pull now as that problem should be fixed.

Actually, the 8723d driver is changing almost daily, so I recommend frequent pulls.

**Comment by nachordez** [comment] 2020-05-13 18:35
Dear lwfinger. Thanks for your work, first of all.
I was trying to build this driver for my rtl8822be device. Just found the read_poll_timeout() problem, and also the solution, and now it builds.
But it does not installs. It builds, but when doing the make install it says:

make[1]: se entra en el directorio '/usr/src/linux-headers-5.4.0-26-generic'
  Building modules, stage 2.
  MODPOST 8 modules
make[1]: se sale del directorio '/usr/src/linux-headers-5.4.0-26-generic'
cp: no se puede efectuar `stat' sobre 'firmware/*.bin': No existe el archivo o el directorio
make: *** [Makefile:86: install] Error 1

It's spanish, so in english something like:
make[1]: entering directory '/usr/src/linux-headers-5.4.0-26-generic'
  Building modules, stage 2.
  MODPOST 8 modules
make[1]: exiting directory '/usr/src/linux-headers-5.4.0-26-generic'
cp: can't be apply `stat' over 'firmware/*.bin': File or directory does not exist
make: *** [Makefile:86: install] Error 1

It seems that something is lacking.

BTW: you propose not to use this but the included driver ib on kernel over 5.2, and I'm on 5.4.
But I have the infamous problem that driver disconnects after suspend. It worked fine on Ubuntu 18.04 on any kernel (including 5.0 and 5.2), but now it does not work on any flavour os version or 5.4 or even the 5.6 included for test. And I was out of any ideas after lots of searching, so I eas trying to try your driver (which helped me so much on older computer...)
Don't know of you can have any idea or any code to add to help on this. Pleas let me know if I can help.

Thnxs

**Comment by lwfinger** [comment] 2020-05-13 19:41
I fixed the typo in Makefile that broke 'sudo make install'.

This repo has all the updates to the drivers for 8723d, 8822b and 8822c that are in kernel 5.7.

I do not use Ubuntu, thus I have no suggestions for your suspend problem. I currently have an RTL8723DE chip in my laptop, and that handles a suspend without loss of connection. My OS is openSUSE Tumbleweed KDE running kernel 5.7.0-rc5.

I am only a volunteer with no knowledge of the internals of these Realtek chips. For issues related to building and installing drivers from this repo, an Issue at GitHub is correct, but problems with the driver itself should be addressed to linux-wireless@vger.kernel.org. From that mailing list, the developers at Realtek will see your issue.

**Comment by lwfinger** [comment] 2020-05-13 19:48
I changed my card to the RTL8822BE and retested hibernate to disk. The NetworkManager applet indicated a disconnect after the restart, but it then reconnected after a few seconds.

The problem is looking more like a user-space problem with Ubuntu 20.04 that with a driver issue. At least with a KDE Plasma desktop and NetworkManager running on openSUSE Tumbleweed, I am unable to duplicate your issue.

**Comment by nachordez** [comment] 2020-05-13 22:47
Thanks for your time and words!
As a matter of fact, trying to install your drivers make mi wifi chipset totally unusable (from the very first boot...). And, even more fun, uninstalling them and reinstalling the kernel, and modules packages can't change lspci of saying that the modules are rtwpci and rtw88-8822be, as when i tryied your drivers, instead of just rtwpci, as it was before. I cannot understand anything. Fortunately, I have several kernel versions installed, and keep mu 5.4.0-28 untouched, so that I can use it and continue using my laptop (without any kind of suspension, of course).
Probably something messed in Ubuntu, as you said. Don't really like Ubuntu, but my wife is used to it, and shares laptop sometimes, so, I was keeping it. 
Thanks anyway, and I'll try to solve it another way, if I can. If I discover something interesting, I'll keep you informed.

**Comment by lwfinger** [comment] 2020-05-14 16:44
I reworked Makefile so that you will be able to make a clean switch between the old  drivers (rtw88 and rtwpci), the drivers in this repo (now named rtw_8723de.ko, rtw_8723d.ko, rtw_8822be.ko, rtw_8822b.ko, rtw_8822ce.ko, rtw_8822c.ko, rtw_core.ko, and  rtw_pci.ko), and drivers from kernels 5.8 and later (same as this repo except rtw88_*, not rtw_*). The setup with rtw88.ko had the drivers for both flavors of RTL8822 combined. This arrangement wasted space, which became more of a problem when RTL8723DE was added. The plan will be to add rtw88_usb.ko for USB devices, which also accounts for the split between rtw_8723d and rtw_8723de. The former will be used for all flavors with the unique code in the ...de, ...du, and probably ...ds.

In the interim, I installed Ubuntu 20.04. Everything worked as expected, including suspend and resume for both the kernel driver and the new one from this repo. It seems that your hardware behaves differently than mine. The 8822BE card on my system is mounted in an Express Card extender slot. During suspension, the power is off. By the time I get logged in after power on, the wifi is up. Does your BIOS offer you either a Wake on Lan or Wake on Wireless option? If so, your device may still be powered, but that should not make any difference.

**Comment by nachordez** [comment] 2020-05-18 11:42
Hi!
Thanks for work and answer!
I've been trying and searching, and I found that problem was originated on difficulties for the same chip working for wifi and bluetooth, and also on the power managment (perhaps even something inherited from the 18.04 installation that I upgraded? Possibly...)
So, with the drivers included in kernel (rtw_pci), blacklisting the modules for wifi and bluetooth, running on init of a little script to use a setpci instruction, and the loading again modules in proper order, everything is working like a charm again.
Thanks again!

**Closed** 2020-06-20 19:44 UTC
