### ISSUE TITLE
rtl8821ae cause cpu soft lockup

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [lwfinger/rtlwifi_new#64] opened 2015-08-24 13:21 UTC
system archlinux
kernel  4.1.6-1-ARCH
recently( at least kernel 4.1.5 and 4.1.6), once I turn on wifi, my laptop will be stuck.
I finally found that kernel module rtl8821ae causes that.
I tried both the module in mainline and  from this project, problem still exists.
I don't know if it is because this rtl8821ae module or other modules depended.

**Comment by lwfinger** [comment] 2015-08-24 14:48
You need more documentation. You either need to use netconsole to get a log, or you need to capture the logging screen. For me, rtl8821ae works fine.

There has been a problem when the PCI devices are used as an AP, but that is fixed in mainline.

**Comment by Alkaid-Benetnash** [comment] 2015-08-24 15:36
mine is a pci device (04:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8821AE 802.11ac PCIe Wireless Network Adapter
)
here is a netconsole log https://cfp.vim-cn.com/ccdL
I successfully connected to an AP,  I turn off the wifi, then everything crashed

**Comment by Alkaid-Benetnash** [comment] 2015-08-24 16:07
ignore the first line, just for testing netconsole

**Comment by lwfinger** [comment] 2015-08-24 16:10
Thanks for the log. I'm a little worried about the i915 involvement in the crash.

Please run either kernel 4.2-rc8 or the latest from Linus's mainline git repo and see if you can duplicate the results. Please use the built-in kernel drivers, not the ones from this repo I also have an i915 graphics adapter, and I do not see the problem as described. My kernel is from the wireless-drivers-next tree with additional pulls from mainline.

**Comment by Alkaid-Benetnash** [comment] 2015-08-25 01:03
Should I compile an entire 4.2 kernel or just rtl modules from that?

**Comment by Alkaid-Benetnash** [comment] 2015-08-25 02:46
I compile 4.2-rc8 from AUR, with bellow kernel and modules, it still crashed......

uname -r
4.2.0-rc8-mainline

modinfo rtl8821ae
filename:       /lib/modules/4.2.0-rc8-mainline/kernel/drivers/net/wireless/rtlwifi/rtl8821ae/rtl8821ae.ko.gz
firmware:       rtlwifi/rtl8821aefw.bin
description:    Realtek 8821ae 802.11ac PCI wireless
license:        GPL
author:         Realtek WlanFAE	<wlanfae@realtek.com>
alias:          pci:v000010ECd00008821sv*sd*bc*sc*i*
alias:          pci:v000010ECd00008812sv*sd*bc*sc*i*
depends:        rtlwifi,rtl_pci,btcoexist,mac80211
intree:         Y
vermagic:       4.2.0-rc8-mainline SMP preempt mod_unload modversions 
parm:           swenc:Set to 1 for software crypto (default 0)
 (bool)
parm:           ips:Set to 0 to not use link power save (default 1)
 (bool)
parm:           swlps:Set to 1 to use SW control power save (default 0)
 (bool)
parm:           fwlps:Set to 1 to use FW control power save (default 1)
 (bool)
parm:           msi:Set to 1 to use MSI interrupts mode (default 1)
 (bool)
parm:           debug:Set debug level (0-5) (default 0) (int)
parm:           disable_watchdog:Set to 1 to disable the watchdog (default 0)
 (bool)

**Comment by lwfinger** [comment] 2015-08-25 15:06
Yes, I did want you to run with the entire 4.2-rc8 kernel.

This problem is mystifying. Please tell me more about the ARCH Linux setup.

Are you using NetworkManager, or some other method to control the wifi?
Exactly what method do you use to turn off the wifi?
Does the same problem happen with the command "sudo rfkill block all"?

**Comment by Alkaid-Benetnash** [comment] 2015-08-25 15:17
I use NetWorkManager, just click the network in settings of gnome for now.
let me try turn off the wifi, I need to prepare for a reboot
4.2-rc8 kernel .config is here https://gist.github.com/Alkaid-Benetnash/04df95115be6ed1d3ebb

**Comment by Alkaid-Benetnash** [comment] 2015-09-02 06:54
So what can I do next, wait for the mainline to fix it?
Or it was only triggered because my own reasons?

**Comment by lwfinger** [comment] 2015-09-02 13:59
As I am the one that fixes mainline problems, you may have to wait a long while.

I have no idea what triggered it; however, I am unable to duplicate your problem. For that reason, fixing it will be difficult. In addition, I am not aware of anyone else reporting such a problem. I cannot rule out some situation in your user space, or your particular mode of operation. Sorry to not have a better explanation or workaround.

For what it is worth, I have never seen the devices renumbered/renamed by rfkill, and that is definitely a function of your user-space code.

**Comment by rtlwifi-linux** [comment] 2015-09-16 06:34
My test environment: kernel 4.1.6-1-ARCH + rtl8821ae module

I try this issue with above testing environment and command netctl start/stop, rfkill unblock/block all.
I also didn't see any system stuck, it works fine with several repeated operations.
So I think this is a single case as so far.

**Comment by jprvita** [comment] 2015-09-25 21:44
I've seen a regression from between 4.1.0 and 4.2.0 that causes a soft lockup on the RTL8821AE during downloads. I have bisected it and reverting the first bad commit fixes the problem for me. I'm going to report this properly in linux-wireless next week, but in the meantime, here is the revert commit (on top of 4.2.0): jprvita/linux@f605f683fb02b29ef889041904f73fc2fcab5b55

**Comment by Alkaid-Benetnash** [comment] 2015-10-16 10:20
Hello, I am surprised to find that my problem is solved after a kernel upgrade   ----  **4.2.3-1-ARCH**
But I was confused by the git log from mainline(torvalds/linux), may I ask for some explanation about this bug?

**Comment by lwfinger** [comment] 2015-10-16 16:03
As far as I know, the fix for RTL8821AE soft lockups has not yet reached mainline. The commit message is as follows:

    rtlwifi: rtl8821ae: Fix system lockups on boot
    
    In commit 1277fa2ab2f9 ("rtlwifi: Remove the clear interrupt routine from all
    drivers"), the code that cleared all interrupt enable bits before setting them
    was removed for all PCI drivers. This fixed an issue that caused TX to be
    blocked for 3-5 seconds. On some RTL8821AE units, this change causes soft
    lockups to occur on boot. For that reason, the portion of the earlier commit
    that applied to rtl8821ae is reverted. Kernels 4.1 and newer are affected.
    
    See http://marc.info/?l=linux-wireless&m=144373370103285&w=2 and
    https://bugzilla.opensuse.org/show_bug.cgi?id=944978 for two cases where
    this regression affected user systems. Note that this bug does not appear on
    any of the developer's setups. For those users whose systems are affected
    by the TX blockage, but do not lock up on boot, a module parameter is added
    to disable the interrupt clear
    
    Fixes: 1277fa2ab2f9 ("rtlwifi: Remove the clear interrupt routine from all drivers")

What part of that do you not understand?

**Comment by Alkaid-Benetnash** [comment] 2015-10-17 15:30
I was wrong. After the second reboot after kernel upgrade, problems were back again.
But it is still weird, the first reboot after kernel upgrade, everything went well, even convinced me to let module rtl8821ae auto loaded when start up. What's more, the start up of the second reboot is fine as well.  But when I turn on wifi after the second reboot, system freezed again and couldn't boot with rtl8821ae auto-loaded. I will try to do this revert manually, not waiting for the mainline.
I used to think my problem was solved but there were no related commits in upstream's git log, so I was confused. But that makes sense now.

**Comment by lwfinger** [comment] 2015-10-17 16:40
Rather than reverting the entire commit, you might apply the correct patch as found at http://marc.info/?l=linux-wireless&m=144380428521948&w=2.

**Comment by wioo** [comment] 2015-11-09 19:03
I almost lost my mind with this error (cpu soft lockup). Took me 1 month or even more to find a solution.  It was msi option (default value 1) -> 0. (kernel 4.3)

**Comment by lwfinger** [comment] 2015-11-09 19:07
Most systems do not need this option set, but in the future you now know to look at ALL the options.

**Comment by Alkaid-Benetnash** [comment] 2015-11-25 13:09
wioo: thank you very much, set msi option to 0 really works. My kernel is 4.4-rc2, now wireless works well.

**Comment by lwfinger** [comment] 2015-11-25 15:55
This setting depends on what computer you have. It would be nice if the "me too" messages listed the make and model for which this option is needed.

**Comment by wioo** [comment] 2015-11-30 16:14
In my case, it was low-end asus notebook X551MA.

**Comment by atombrom** [comment] 2015-12-08 09:34
Thanks for noting this issue. Appears to be the same problem for me with Asus TX201LA laptop with Realtek RTL8821AE when upgrading from 4.1.3-100.fc21.x86 (or FC23 install) hangs.  Confirming pci=nomsi works for me
http://forums.fedoraforum.org/showthread.php?t=306441
On this issue I have had an open bugzilla filed on this for a while
https://bugzilla.redhat.com/show_bug.cgi?id=1269335 .

Any suggestions for getting this bug resolved more permanently for future linux users?

**Comment by lwfinger** [comment] 2015-12-08 15:45
The issue is with your hardware. An overwhelming percentage of users find that MSI works on their hardware, and it performs better. Complain to your computer vendor.

**Closed** 2016-08-02 06:31 UTC
