### ISSUE TITLE
reduced range problem(weak wifi strength) in ubuntu 14.04 -amd64 with 02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter

### ISSUE THREAD

**Issue by jagabandhumishra** [lwfinger/rtlwifi_new#252] opened 2017-07-11 02:36 UTC
please someone suggest me how to fix it

**Comment by mirh** [comment] 2017-08-08 19:02
My educate guess is that you can close this as a duplicate of #263

**Closed** 2018-10-13 04:48 UTC
