### ISSUE TITLE
Wifi doesn't work after going into sleep mode in hp-ab032tx in ubuntu 15.04

### ISSUE THREAD

**Issue by doomers** [lwfinger/rtlwifi_new#99] opened 2016-02-27 10:00 UTC
wifi without this driver is a a dream on my hp-ab032tx,so thank you guys.but  now i am having a another issue that when it goes into sleep mode and i logged in again,wi-fi doesn't work and when i click on wifi icon (wifi disabled by hardware switch) appears. i have restart my system every time it goes into sleep mode. please fix this soon

**Comment by lwfinger** [comment] 2016-02-27 17:38
If your wifi is disabled by the switch, this is not a problem that I can fix. You need to look at either rfkill or the wmi routines. The latter are specific to your particular computer model. I do not have this problem on my Toshiba laptop.

**Comment by rahul357** [comment] 2016-02-28 06:16
Yeah but wifi works fine before going into sleep mode. And I has to restart again in order to get wifi working. 
If this is a problem in my hardware how could it run before going into sleep mode or it totally works fine on Windows.

**Comment by lwfinger** [comment] 2016-02-28 06:29
It is NOT hardware. It is software that is not part of this driver.

**Comment by rahul357** [comment] 2016-02-28 06:54
So will buying a  new wifi adapter from Amazon Will works .

**Comment by lwfinger** [comment] 2016-02-28 16:40
Perhaps. Not all wifi adapters have Linux drivers. In addition, if your system is setting the rfkill switch, no wifi or BlueTooth will work.

After putting the machine to sleep, run the command 'rfkill list all'. If any blocks are "yes", that is the problem.

If you remove and reload the driver after coming back from sleep, do you have the same problem. As you have never told me what card you have, I cannot give you the exact commands.

**Comment by rahul357** [comment] 2016-03-01 18:02
sorry for the late reply, now  i am getting what are you trying to say, my
driver card is rtl8723be, please save me,as only you can, i ctoo had tried
external wifi adapter but it also doesn't after it goes to sleep
mode.

**Comment by lwfinger** [comment] 2016-03-02 01:46
Do you see the pattern? It seems to me that no matter what card or driver is being used,  wireless fails to wake up after the computer does. OK, this time you told me what card you are using, but you failed to run the command that I needed to be run. Please run 'rfkill list all' and post the output!!

**Comment by rahul357** [comment] 2016-03-02 01:51
$ rfkill list
0 : phy0
Soft Block :no
Hard Block : Yes
Now tell me the commands, I has heard that we had to disable wifi in BIOS I
did that too but  it doesn't work either.

**Comment by lwfinger** [comment] 2016-03-02 01:59
That "hard block" says that the computer thinks that the wireless enable switch os OFF. If you only can control that with a Fn key, then the problem is likely the module named wmi-hp. You computer may be too new for the existing code to work with the kernel you are running.

Any routines that control rfkill blocking are well outside my expertise. From what I can see, the wifi driver is doing exactly what it should. If soft, or hard, blocking is enabled, the wifi MUST be turned off.

**Comment by rahul357** [comment] 2016-03-02 02:03
So  there isn't any solution for the same, I mean there has to be some,
I heard that you has developed new drivers for my card no ,can you tell me
the commands for that or some other that may work

**Comment by lwfinger** [comment] 2016-03-02 02:34
It is not the wifi driver. When you turn the wifi off, my driver does what it is told. That is what is happening, even if you do not intend for it to happen. It is some other part of your kernel and/or distro that I do and cannot control.

You need to google the problem for your model laptop.Perhaps some other user has solved the problem. My laptop is a Toshiba, and the problem does not happen. Sorry, but I will not be able to help you.

**Comment by rahul357** [comment] 2016-03-02 16:07
No ,but there must be something you can do because before installing
lwfinger driver wifi doesn't goes off every time i t got suspended or goes
into sleep mode

**Comment by rakshithravi1997** [comment] 2016-05-10 20:52
I have the exact same laptop. How exactly did you get wifi working? I installed this driver but I'm still facing speed and connectivity issues among other issues. I'm in a similar situation you were. Could you point out your settings or help me get mine setup?

**Comment by lwfinger** [comment] 2016-12-02 20:18
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Closed by lwfinger** 2016-12-02 20:18 UTC
