### ISSUE TITLE
RTL 8821AE Ubuntu 16.04 kernel 4.6 (but others, too) frequent short connectivity loss

### ISSUE THREAD

**Issue by Brainpiercing** [lwfinger/rtlwifi_new#185] opened 2016-12-09 12:18 UTC
On my HTPC I'm suffering from frequent connectivity loss. Ever since building this computer I've had issues with the wifi. Serves me right for not checking linux support for the motherboard, an Asrock miniITX with wifi RTL8821ae and BT onboard. BT seems to be working fine.

I first installed Ubuntu 14.04, and installed RTLwifi_new to even get AC wifi support. It worked, but there were always issues. It used to be a loss of connectivity every hour or so. Eventually I updated to Ubuntu 16.04, and then recently updated the Kernel to 4.6 Lowlatency for some audio issues. RTLwifi_new has always been compiling fine, but the connectivity losses have been getting worse. Now it's every few minutes. There is no change in status in network manager, nor do I need to reconnect. It just stops for a few seconds - but long enough to interrupt playback of videos. 

Edit: Some more info:
The router this connects to is a Cisco EA6400 (I know a questionable purchase) on the 5G network. 
The displayed link speed is 200Mbs - it used to show 433 before Ubuntu 16.04.
I tried playing with the "options rtl8821ae fwlps=N ips=N swlps=Y msi=Y" in rtl8821ae.conf, but eventually removed that again, as it made things worse - or seemed to.

I'm attaching the output of the wifi-script. 
[wireless-info.txt](https://github.com/lwfinger/rtlwifi_new/files/642098/wireless-info.txt)

I would be very grateful if someone could look into this. Thanks!

**Comment by efkan** [comment] 2016-12-11 10:18
This is **not an exact solution** or **a workaround**. With using these old files my connection drops more rarely. Sometimes it takes 30 hours, sometimes 2 hours.

https://www.dropbox.com/s/f2itafir5vd05ag/rtlwifi_old.tar.gz?dl=0

I use they files for `RTL8723BE` on kernel `4.4.0-53-generic`. Maybe it works for you too.

1. Download and extract the files
2. Enter the directory that contains the extraxted files
3. First `make clean`
4. `make`
5. `sudo make install`
6. `sudo modprobe rtl8821ae -r`
7. `sudo modprobe rtl8821ae ant_sel=2`
8. Reboot.

**Comment by Brainpiercing** [comment] 2016-12-11 13:51
Thanks efkan. I'll check it out. It's the first time I've read bout ant_sel being used for RTL8821AE, although this is a dual antenna motherboard. 

I'm thinking occasionally this issue could be entirely the same as #172, as I also do get slowdowns, without complete loss of connectivity. However, it alternates between just slowing down and going right down to 0 in my case. 

Is there some good tool to monitor network performance with a log? Possibly something that logs other things, too. Kern.log or dmesg show nothing.

**Comment by efkan** [comment] 2016-12-11 14:09
There are other entries and "thoughts" on other sites:

http://askubuntu.com/a/847463/411321

http://askubuntu.com/questions/635625/how-do-i-get-a-realtek-8723be-wireless-card-to-work

[marked as Solved] https://ubuntuforums.org/showthread.php?t=2329067

[an article as solution] http://www.andersaaberg.dk/2015/getting-wireless-to-stop-disconnecting-on-hp-probook-430-g2-on-ubuntu-14-04-linux/

I'll try the article. We'll see whether it's a solution or not :)

**Comment by lwfinger** [comment] 2016-12-11 15:17
Note: ant_sel is enabled ONLY for rtl8723be. If you look at dmesg when it is used with rtl8821ae, you should see an entry about an incorrect parameter.

**Comment by Brainpiercing** [comment] 2016-12-11 15:46
Thanks!

lwfinger, could you please clarify one thing (I'm not very well versed in how git projects are organised): Does the main branch contain the new realtek code you were writing about, which is supposed to make it unnecessary to change the powersave options? This is a desktop computer, I would disable powersave by default, but whenever I do change the settings the connection loss is worse, for instance, it does not recover without a reboot, whereas with default options it will usually come back after disabling wifi and re-enabling it.

**Comment by lwfinger** [comment] 2016-12-11 16:30
There is no standard way that git projects are organized.

The branch "master", which is the main one, does contain the fix for power save. You should not need to use any such parameters when running that version.

**Comment by efkan** [comment] 2016-12-11 16:47
The solution which is mentioned on the article did not solve my issue. My wifi has dropped the connection in 90 minutes. Unfortunately..

**Comment by Brainpiercing** [comment] 2016-12-11 18:36
I'm looking at my network usage with ntopng. Now while reading a large file from the LAN it will drop from whatever rate it was going at - a few Mbps - to a few hundred BPS for a few seconds. There is nothing in Kern.log or syslog to correlate.

**Comment by Brainpiercing** [comment] 2016-12-11 19:57
I tried to use rsyslogd in debug mode to get some more info, but I can't figure out how to make it give me some meaningful information. The logs are just full of stuff related to rsyslogd itself. 

Can anyone give me a hint, there?

**Comment by kenzolo** [comment] 2017-03-14 19:15
Finally solved my rtl8821ae connection issue
solution:

1- open /etc/NetworkManager/NetworkManager.conf as root and 
disable the Network Manager for your wireless interface adding these lines

[keyfile]
unmanaged-devices=mac:b3:e40:92:68:b1:33    (REMEMBER TO USE LOWERCASE and replace with your wireless mac address)

2-install wicd network manager
sudo apt-get install wicd

reboot

**Comment by mirh** [comment] 2017-04-02 21:36
Isn't this dupe of #183 then?

**Comment by franzejr** [comment] 2017-09-14 16:13
Still having the issue :(

**Comment by michal3141** [comment] 2018-01-06 19:40
I have the very same issue as efkan. My wifi still disconnects but more infrequently like every 90 minutes or so. Is there a way to totally remove this issue for rtl8821ae ?

**Comment by nikolas** [comment] 2018-01-26 18:22
@AlexisTM and everyone, have you tried commenting out this call to `enable_aspm()` in `hw.c`? https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/drivers/net/wireless/realtek/rtlwifi/rtl8821ae/hw.c#n1981  This resolves the problem on my Lenovo Ideapad 320-15ABR.

**Comment by AlexisTM** [comment] 2018-01-26 21:22
Oh! I will test that, thanks for the suggestion @nikolas ;)

**Comment by michal3141** [comment] 2018-01-29 11:30
@nikolas Does it solve the problem completely? I mean I have the power management turned off on the wireless interface but still my network is dropping from time to time. Sometimes nothing happens over 3h and then I am getting disconnected which is annoying because I cannot really predict when the disconnection is going to happen.

**Comment by pbgnz** [comment] 2018-04-30 01:47
Hey guys, I recently installed Ubuntu 18.04 LTS and my WiFi connection is working fine throughout the day with the rtl8821ae driver. I can watch YouTube videos and download things without connectivity loss. 

However, ever time I turn on my computer I have to manually set the WiFi driver using the 
`sudo modprobe rtl8821ae` command and I do not like doing it. Is there a way to fix this?

**Comment by lwfinger** [comment] 2018-04-30 06:16
You likely have some file in /etc/modprobe.d/ that is blacklisting rtl8821ae or some component it needs.

**Comment by thread13** [comment] 2018-07-03 04:22
Had a similar problem with a "stock" 16.04 driver -- was substantially improved by switching to one from this repository, however, still with problems described in https://patchwork.kernel.org/patch/9951511/ -- periodic disconnects and packets periodically cached _somewhere_ -- with ping delays going to 10-30 _seconds_ high.

Latest 8821ae update from Feb 5th along with the patch discussed in [9951511](https://patchwork.kernel.org/patch/9951511/) seems to solve it.

@lwfinger -- btw, am I right that modinfo for `ips` paramater shall read "Set to **1** to not use link power save (default 1)" -- that is, shall have an inverted meaning? From the code -- it looks as it goes to `rtlwifi`'s `inactiveps`, that is, `ips==1` shall mean _powersave is inactive_ .

Also, I wonder if it would make sense to add a module parameter to optionally disable `..enable_aspm..` in `hw.c::rtl8821ae_hw_init()` ?  

Anyway -- a terrific job on nailing this down!

**Comment by thread13** [comment] 2018-07-03 15:58
Admittedly I'm not a native speaker, so I checked it with Google. `define:inactive` returns _"not working; inoperative"_, therefore "inactive power save" should probably mean "power save not working". If `inactiveps <-> ips` is `true` by default, then I would read it as _"inactive power save: on (true)"_. it indeed sounds correct with no ambiguity. However, my conclusion would be that power save is _inactive (disabled)_ by default. Hence the question.

As for `enable_aspm` -- is that a general kernel parameter? You mean, the global one `pcie_aspm` in the kernel ?

**Closed** 2020-07-06 19:50 UTC
