### ISSUE TITLE
rtl8723de bluetooth works correctly only when wifi is switched off

### ISSUE THREAD

**Issue by finkandreas** [lwfinger/rtlwifi_new#382] opened 2018-07-26 09:43 UTC
I'm on the the extended branch newest version and have linux-4.17.5 as kernel. The module `rtl8723de` is loaded with the option `ant_sel=2`.
When I'm connected to a wifi network, bluetooth works only, when I put my bluetooth receiver on my notebook, i.e. it stops working over a distance > 20cm (connection is lost).
When I turn off wifi with NetworkManager (i.e. rfkill is used I think), bluetooth works just fine even for long distances, tested with > 5m through 2 walls.
For clarification: I do not reload the module, I just turn off the wifi, and I can see in the output of `rfkill` that my wifi is `SOFT blocked` and `HARD unblocked`

Do you think it has something to do with `ant_sel=2`? Is there anything that I can run for debugging into the issue? Is it worth to open the laptop and change the antenna port on the wifi card?

**Comment by lwfinger** [comment] 2018-07-26 13:42
This comment would be much better handled by the standard mailing list for wifi (linux-wireless@vger.kernel.org) and Bluetooth (linux-bluetooth@vger.kernel.org).

The ant_sel option only affects the radio used by the RTL8723DE. What you describe is a separate device, which has its own radio. Any interaction between the antenna connection for the wifi radio and a separate BT radio seem unlikely, other than the two radios will be both trying to compete for the 2.4G radio spectrum. Having a separate transmitter so close may be the issue. The BT interference routines in the wifi driver should handle this issue, and that may be the problem. I have no way of testing this problem - I do not have ant RTL8723DE devices. Sending the issue to the mailing lists noted above, including specifying the make and model of your BT device, should help in resolving the issue.

Note that any rfkill block, either HARD or SOFT, is supposed to stop ALL radios. The fact that stopping wifi does not stop BT is a bug in my estimation.

**Closed by lwfinger** 2018-07-26 13:42 UTC

**Comment by glodfinch** [comment] 2018-09-24 09:55
@lwfinger, apologies to bother you on this closed issue where you were already pretty clear. I can see that @finkandreas did send a message to the mailing list, but unfortunately didn't get a response - and this issue is still present as late as 4.18.9. As this is all pretty new to me, is there any data, or testing you'd be aware would be helpful for the mailing list users to have, or is it primarily waiting for someone willing and able to come across this issue?

**Comment by Harshdeep4295** [comment] 2018-11-30 11:32
So how can one workout on this ??? since I am getting the same problem here........

**Comment by padlych** [comment] 2019-01-30 21:37
Linux kernel 4.17.3-041703-generic. The same situation. Bluetooth began to work with 
[   10.647823] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_config.bin
[   10.820288] Bluetooth: hci0: rtl: loading rtl_bt/rtl8723d_fw.bin
But link quality is poor (about 10%). So headset do not work with A2DP profile (sound is buggy because bandwidth is poor)

**Comment by dubhater** [comment] 2019-07-26 09:26
Would it help to install a second antenna?

**Comment by lwfinger** [comment] 2019-07-26 15:35
Possibly; however, on my card, there is only one connector, thus that would not be an option.

Realtek has a new driver for rtl8723de close to introduction. It will correctly handle the BT coexistence. When it is published, I will add it to the rtw88 branch of this repo.

**Comment by pandey246** [comment] 2019-07-27 16:41
<pre><font color="#EF2929"><b>root@pandeyji</b></font>:<font color="#729FCF"><b>~/Downloads/compat-wireless-2010-06-26-p</b></font># sudo make unload
/bin/sh: 1: [: -gt: argument expected
/bin/sh: 1: test: -ge: unexpected operator
/sbin/modprobe: invalid option -- &apos;l&apos;
/sbin/modprobe: invalid option -- &apos;l&apos;
Stoping bluetooth service..
[<font color="#4E9A06"> ok </font>] Stopping bluetooth (via systemctl): bluetooth.service.
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:bluetoothd(8)

Jul 27 22:11:17 pandeyji bluetoothd[1575]: Terminating
Jul 27 22:11:17 pandeyji systemd[1]: Stopping Bluetooth service...
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Stopping SDP server
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Exit
Jul 27 22:11:17 pandeyji systemd[1]: bluetooth.service: Succeeded.
Jul 27 22:11:17 pandeyji systemd[1]: Stopped Bluetooth service.
Hint: Some lines were ellipsized, use -l to show in full.
Unloading mac80211...
modprobe: FATAL: Module mac80211 is in use.
Unloading cfg80211...
modprobe: FATAL: Module cfg80211 is in use.
Unloading rfcomm...
Unloading bnep...
Unloading btusb...
Unloading bluetooth...
modprobe: FATAL: Module bluetooth is in use.
<font color="#EF2929"><b>root@pandeyji</b></font>:<font color="#729FCF"><b>~/Downloads/compat-wireless-2010-06-26-p</b></font># sudo make load
/bin/sh: 1: [: -gt: argument expected
/bin/sh: 1: test: -ge: unexpected operator
/sbin/modprobe: invalid option -- &apos;l&apos;
/sbin/modprobe: invalid option -- &apos;l&apos;
Stoping bluetooth service..
[<font color="#4E9A06"> ok </font>] Stopping bluetooth (via systemctl): bluetooth.service.
● bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: man:bluetoothd(8)

Jul 27 22:11:17 pandeyji bluetoothd[1575]: Terminating
Jul 27 22:11:17 pandeyji systemd[1]: Stopping Bluetooth service...
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…urce
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Endpoint unregistered: sender=:1…Sink
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Stopping SDP server
Jul 27 22:11:17 pandeyji bluetoothd[1575]: Exit
Jul 27 22:11:17 pandeyji systemd[1]: bluetooth.service: Succeeded.
Jul 27 22:11:17 pandeyji systemd[1]: Stopped Bluetooth service.
Hint: Some lines were ellipsized, use -l to show in full.
Unloading mac80211...
modprobe: FATAL: Module mac80211 is in use.
Unloading cfg80211...
modprobe: FATAL: Module cfg80211 is in use.
Unloading bluetooth...
modprobe: FATAL: Module bluetooth is in use.
/sbin/modprobe: invalid option -- &apos;l&apos;
/sbin/modprobe: invalid option -- &apos;l&apos;
Loading ipw2100...
modprobe: FATAL: Module ipw2100 not found in directory /lib/modules/4.19.0-kali5-amd64
Loading ipw2200...
Loading libertas_cs...
Loading usb8xxx...
Loading p54pci...
Loading p54usb...
Loading adm8211...
Loading zd1211rw...
Loading rtl8180...
modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.19.0-kali5-amd64
Loading rtl8187...
Loading p54pci...
Loading p54usb...
Loading iwl3945...
Loading iwlagn...
modprobe: FATAL: Module iwlagn not found in directory /lib/modules/4.19.0-kali5-amd64
Loading ath...
Loading ar9170usb...
Loading rtl8180...
modprobe: FATAL: Module rtl8180 not found in directory /lib/modules/4.19.0-kali5-amd64
Loading rtl8187...
Loading rt2400pci...
Loading rt2500pci...
Loading rt61pci...
Loading rt2500usb...
Loading rt73usb...
Loading rndis_wlan...
Loading at76_usb...
modprobe: FATAL: Module at76_usb not found in directory /lib/modules/4.19.0-kali5-amd64
Loading mwl8k...
Loading mac80211_hwsim...
Loading at76c50x_usb...
Loading bluetooth...
Loading btusb...
Loading l2cap...
modprobe: FATAL: Module l2cap not found in directory /lib/modules/4.19.0-kali5-amd64
Loading sco...
modprobe: FATAL: Module sco not found in directory /lib/modules/4.19.0-kali5-amd64
Loading hidp...
Loading rfcomm...
Loading bnep...
./scripts/load.sh: line 21: athload: command not found
./scripts/load.sh: line 23: b43load: command not found
Starting bluetooth service..
[<font color="#4E9A06"> ok </font>] Starting bluetooth (via systemctl): bluetooth.service.
<font color="#8AE234"><b>●</b></font> bluetooth.service - Bluetooth service
   Loaded: loaded (/lib/systemd/system/bluetooth.service; disabled; vendor preset: disabled)
   Active: <font color="#8AE234"><b>active (running)</b></font> since Sat 2019-07-27 22:11:29 IST; 98ms ago
     Docs: man:bluetoothd(8)
 Main PID: 3250 (bluetoothd)
   Status: &quot;Running&quot;
    Tasks: 1 (limit: 4915)
   Memory: 1.0M
   CGroup: /system.slice/bluetooth.service
           └─3250 /usr/lib/bluetooth/bluetoothd

Jul 27 22:11:29 pandeyji bluetoothd[3250]: Starting SDP server
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Bluetooth management interface 1…ized
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>Sap driver initialization failed.</b></font>
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>sap-server: Operation not permit… (1)</b></font>
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.6…urce
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.6…Sink
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.4…urce
Jul 27 22:11:29 pandeyji bluetoothd[3250]: Endpoint registered: sender=:1.4…Sink
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>RFCOMM server failed for Headset…(98)</b></font>
Jul 27 22:11:29 pandeyji bluetoothd[3250]: <font color="#EF2929"><b>RFCOMM server failed for :1.62/P…(98)</b></font>
Hint: Some lines were ellipsized, use -l to show in full.
<font color="#EF2929"><b>root@pandeyji</b></font>:<font color="#729FCF"><b>~/Downloads/compat-wireless-2010-06-26-p</b></font># 
</pre>

**Comment by pandey246** [comment] 2019-07-27 16:44
in above code the problem is not solved as only my phone is able to connect with my laptop.My headphone is not able to connect with laptop.and the problem is that after reboot bluetooth becomes inactive and i need to follow the above steps again,everytime.I have rtl8723de chipset.Plz help me.

**Comment by lwfinger** [comment] 2019-07-27 18:08
See comments in issue #466.
