### ISSUE TITLE
Can not install the RTL8723DE module in ubuntu16.04

### ISSUE THREAD

**Issue by neetupandey20** [lwfinger/rtlwifi_new#570] opened 2020-05-05 07:51 UTC
Hello Team,
I am unable to install RTL8723DE module in my ubuntu16.04 please help me out in this.
i got this error when i run make install
make: Entering directory '/usr/src/linux-headers-4.15.0-99-generic'
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/base.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/cam.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/core.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/debug.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/efuse.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/ps.o
  CC [M]  /var/lib/dkms/rtlwifi-new/0.6/build/rc.o
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .alloc = rtl_rate_alloc,
           ^
/var/lib/dkms/rtlwifi-new/0.6/build/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
scripts/Makefile.build:330: recipe for target '/var/lib/dkms/rtlwifi-new/0.6/build/rc.o' failed
make[1]: *** [/var/lib/dkms/rtlwifi-new/0.6/build/rc.o] Error 1
Makefile:1577: recipe for target '_module_/var/lib/dkms/rtlwifi-new/0.6/build' failed
make: *** [_module_/var/lib/dkms/rtlwifi-new/0.6/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.15.0-99-generic'

**Comment by karthiksuresh181** [comment] 2020-05-05 08:48
I'm also facing the same issue.

**Comment by burdi01** [comment] 2020-05-05 09:33
There are a LOT of closed issues about this symptom.

**Comment by lwfinger** [comment] 2020-05-05 15:34
Yes there are a lot of closed issues; however, I would never expect any of my learned users to do any research before complaining. :) But, no matter, all of them are now outdated.

The issue is that kernel mainline merged a fix that changed the number of arguments for the callback routine rtl_rate_alloc(). Because this change fixed a bug, it was backported to the stable kernels. Suddenly, it was no longer possible to test LINUX_VERSION_CODE to see which version of the code that the user has. To overcome the dilemma, I was recommending that users with the old form check out an older version of the code.

That is no longer necessary. I added some new code to Makefile that tests the definition of the routine in the include directory, and defines a special symbol if there is only one argument for the routine. The code in rc.c then tests that special symbol. This should work on all recent kernels.

Just do a 'git pull' and your drivers should build. If you downloaded a zip file, the you will need to do it all over again; however, before doing that, I suggest learning how to use git. Zip files are SO Windows. We are better than that!!

**Closed by lwfinger** 2020-05-05 15:34 UTC

**Comment by farseen79** [comment] 2020-05-20 12:28
cybersoldier@kali:~/rtlwifi_new$ make
grep: /lib/modules/5.6.0-kali1-amd64/build/include/net/mac80211.h: No such file or directory
make -C /lib/modules/5.6.0-kali1-amd64/build M=/home/cybersoldier/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-5.6.0-kali1-amd64'
grep: /lib/modules/5.6.0-kali1-amd64/build/include/net/mac80211.h: No such file or directory
  CC [M]  /home/cybersoldier/rtlwifi_new/rc.o
/home/cybersoldier/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  336 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/home/cybersoldier/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[3]: *** [/usr/src/linux-headers-5.6.0-kali1-common/scripts/Makefile.build:273: /home/cybersoldier/rtlwifi_new/rc.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.6.0-kali1-common/Makefile:1696: /home/cybersoldier/rtlwifi_new] Error 2
make[1]: *** [/usr/src/linux-headers-5.6.0-kali1-common/Makefile:180: sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.6.0-kali1-amd64'
make: *** [Makefile:88: all] Error 2

i have the same issue, my kernal version is 5.6.0

**Comment by AmanAjayVarma** [comment] 2020-05-26 03:07
grep: /lib/modules/4.19.0-9-amd64/build/include/net/mac80211.h: No such file or directory
make -C /lib/modules/4.19.0-9-amd64/build M=/home/aman/Documents/program/rtlwifi_new modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-9-amd64'
grep: /lib/modules/4.19.0-9-amd64/build/include/net/mac80211.h: No such file or directory
  CC [M]  /home/aman/Documents/program/rtlwifi_new/rc.o
/home/aman/Documents/program/rtlwifi_new/rc.c:336:11: error: initialization of ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *)’ [-Werror=incompatible-pointer-types]
  .alloc = rtl_rate_alloc,
           ^~~~~~~~~~~~~~
/home/aman/Documents/program/rtlwifi_new/rc.c:336:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-4.19.0-9-common/scripts/Makefile.build:309: /home/aman/Documents/program/rtlwifi_new/rc.o] Error 1
make[3]: *** [/usr/src/linux-headers-4.19.0-9-common/Makefile:1537: _module_/home/aman/Documents/program/rtlwifi_new] Error 2
make[2]: *** [Makefile:146: sub-make] Error 2
make[1]: *** [Makefile:8: all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-9-amd64'
make: *** [Makefile:88: all] Error 2

I also have this problem in 4.19.0-9-amd64

**Comment by lwfinger** [comment] 2020-05-26 04:01
This week, you have two choices. You can edit rc.c, find the line with the error, and follow the instructions there, or you can switch to branch rtw88.

One thing to consider is that the extended branch will disappear later this week, and I will ignore any questions about it.

**Comment by AmanAjayVarma** [comment] 2020-05-28 04:16
I have solved my problem with this -> 

https://github.com/lwfinger/rtlwifi_new/issues/554#issuecomment-622511700

and this ->

https://askubuntu.com/a/554636/992377
