### ISSUE TITLE
Bluetooth not working with RTL8723BE

### ISSUE THREAD

**Issue by cybernova** [lwfinger/rtlwifi_new#18] opened 2014-11-27 16:06 UTC
Hello, 
I'm using Ubuntu 14.04 LTS with this last driver which is working really good for Wi-Fi but the bluetooth is still not working. It does not find any device and devices do not find it.

```
andrea@Workstation:~$ modinfo btcoexist 
filename:       /lib/modules/3.13.0-40-generic/kernel/drivers/net/wireless/rtlwifi/btcoexist/btcoexist.ko
description:    Realtek 802.11n PCI wireless core
license:        GPL
author:         Larry Finger	<Larry.FInger@lwfinger.net>
author:         Realtek WlanFAE	<wlanfae@realtek.com>
author:         Page He	<page_he@realsil.com.cn>
srcversion:     97A952CB16550F2BF298DD8
depends:        rtlwifi
vermagic:       3.13.0-40-generic SMP mod_unload modversions 

```
Thank You

**Comment by akashpal21** [comment] 2015-01-02 10:22
Hello, Wifi Driver on rtl8723be works great; Kernel : 3.13.0-43-generic. Bluetooth problem was noted, but is solved by the <a href=https://github.com/troy-tan/driver_store/tree/master/bluetooth/8723BE> driver </a> thanks troy-tran :+1:

**Comment by WhiteHatAlister** [comment] 2015-01-04 22:48
hi guys.
affected by this one.
debian 8, kernel 3.16.0-4-amd64.
this tarball installed over, new kernel modules, no change.
count on me for hcidump logs etc.

**Comment by lwfinger** [comment] 2015-01-05 01:37
Several things you should know:
1. The standard BT driver in the kernel will not work with any of the Realtek BT devices. It must be blacklisted or replaced.
2. The drivers in this repo do not include any BT drivers.
3. There are Realtek BT drivers in the git repo at http://github.com/lwfinger/rtl8723au_bt.git. The drivers in the "new" branch may work with your device. If not, try the one embedded in file linux_bt_usb_2.10.20140212_azurewave.rar.
4. I have had no success with any of these BT drivers, and I will be unable to help.

**Comment by WhiteHatAlister** [comment] 2015-01-05 01:42
@lwfinger fine then!
I have downloaded rtl8723au_bt-new branch and checked out Makefile.
It seems it overwrites btusb so there is no need to blacklist in this particular case, right?
I have seen other pieces of coded that try to build rtk_btusb but this seems not the case.

**Comment by lwfinger** [comment] 2015-01-05 03:10
As long as you use the one from the new branch, then a blacklist is not necessary. If you try a solution that make rtk_btusb, then you will need the blacklist. As long as you can keep track, then it is OK.

**Comment by sunny0** [comment] 2015-01-07 04:34
@WhiteHatAlister 
Any luck with the new branch? I've tried it against 3.18 and it behaves just as you described for 3.16

**Comment by cslotterback** [comment] 2015-01-15 01:37
I installed troy-tan's bt drivers, and now my bluetooth won't even turn on, let alone pair with anything :)

I was having the original problems of no devices found with this realtek chip, however this is not a USB dongle, this is from a barebones gigabyte HTPC, so it is listed under lspci

>02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter

I tried a host of things before figuring I'd give the usb driver a make-install go, now nothing (bluetooth related) works. I am not too experienced in drivers, any thoughts on how to get back to a stable state, and possibly get bt turned on and paired?

**Comment by lwfinger** [comment] 2015-01-15 01:45
If you want to restore what you had, reinstall the kernel package from your distro. As to the BT, I have no ideas as I have had no time to work with anything but the RTL8723AE.

**Comment by kyle--xu** [comment] 2015-01-15 02:58
@cslotterback
Please provide the output of lsusb and kernel log

**Comment by cslotterback** [comment] 2015-01-15 23:18
@kyle--xu 
>slotterback@slottermedia:~$ cat lsusb.txt 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0518:0001 EzKEY Corp. USB to PS2 Adaptor v1.09
Bus 001 Device 003: ID 04b4:1224 Cypress Semiconductor Corp. 
Bus 001 Device 002: ID 13d3:3410 IMC Networks 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

>slotterback@slottermedia:~$ cat dmesg.txt | grep -i blue
[    1.441348] usb 1-2: Product: Bluetooth Radio 
[   15.664054] Bluetooth: Core ver 2.17
[   15.664131] Bluetooth: HCI device and connection manager initialized
[   15.664147] Bluetooth: HCI socket layer initialized
[   15.664152] Bluetooth: L2CAP socket layer initialized
[   15.664162] Bluetooth: SCO socket layer initialized
[   15.678528] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   15.678534] Bluetooth: BNEP filters: protocol multicast
[   15.678546] Bluetooth: BNEP socket layer initialized
[   27.599331] Bluetooth: RFCOMM TTY layer initialized
[   27.599347] Bluetooth: RFCOMM socket layer initialized
[   27.599360] Bluetooth: RFCOMM ver 1.11

@lwfinger 
I'd like to avoid that for now, I've done a bit of work I'd rather not replicate for now

**Comment by janfromdd** [comment] 2015-01-27 11:53
Hello, yesterday I got Bluetooth working on a HP ProBook 430 with RTL8723BE, here is how:

1. Setup a fresh Ubuntu 14.04 from Live Image
2. Replaced the original WiFi driver with the files from <a href="https://github.com/lwfinger/rtlwifi_new">this repository</a> (downloaded master branch as zip and installed with <b>sudo make install</b>
3. reboot
4. Downloaded <a href="https://github.com/troy-tan/driver_store/tree/master/bluetooth/8723BE">BT driver by troy-tan</a> as rar file
5. Installed it carefully as described in the Readme file
6. reboot

No changes on other packages were required (bluez-..., blueman, etc.)

The <b>rtlwifi_new</b> fixed my WiFi connection which was unstable with the Ubuntu original drivers. The <b>BT USB driver</b> by troy-tan enabled my system to find and pair bluetooth devices.

<p><b>Thanks to you guys for the good work!</b></p>

**Comment by lwfinger** [comment] 2015-01-30 21:11
We try to please. Unfortunately, it sometimes takes a long time.

I will now be working on getting the Realtek BT code into the kernel. As a first step, I have moved the BT driver of troy-tan into the troy branch of this repo. It is named btusb but otherwise it is the same driver. It has been cleaned up a little, but it should still work. Please switch to that branch, test, and let me know.

My future work on this driver will be to merge the Realtek-specific parts into the regular btusb driver. I probably will not announce when I make changes. Please do regular pulls from this repo.

**Comment by lwfinger** [comment] 2015-01-30 21:12
I forgot to say that I have no real way to test this driver. I have no devices with which I can do a meaningful data exchange. I am limited to scanning, and finding local cell phones and my TV.

**Comment by Zophar78** [comment] 2015-01-31 21:23
Hello.. I landed here yesterday evening (trying to get my BT device working on my new laptop -> Ubuntu 14.04). The BT driver from troy-san allowed me finally to pair my devices (the connections seems not stable but at least this was the ONLY driver i found that scan/show other devices). 
I give a try on troy branch but I see no "btusb" (or "rtk_btusb") driver related source... Did i miss something?

**Comment by lwfinger** [comment] 2015-02-01 00:59
You need to use the troy branch of http://github.com/lwfinger/rtl8723au_bt.git. Despite the name, its driver is for all Realtek BT devices.

**Comment by janfromdd** [comment] 2015-02-07 13:28
<i>1. The standard BT driver in the kernel will not work with any of the Realtek BT devices. It must be blacklisted or replaced.</i>
I wonder how this is done, how do i replace a driver?

**Comment by lambertdw** [comment] 2015-02-07 15:08
When from USB  I installed ubuntu 14.04 on this thinkpad w540 with 2x2 
antenna bluetooth connected to other devices.  I installed 
rtlwifi_new-troy from github to enable the wireless LAN and now I think 
bluetooth no longer works, but since I don't know how bluetooth should 
work I can't be sure.

**Comment by pitakill** [comment] 2015-03-11 00:53
@janfromdd 
When you build the module and when you make the instruction:
sudo make install
The program replace the module for you.

**Comment by lsannin** [comment] 2015-04-09 18:43
Hello, I juts update the kernel of ubuntu to 3.16.0-34-generic and the bluetooth not works now, some help please.
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter

**Comment by lwfinger** [comment] 2015-04-09 18:52
Since Ubuntu started its abominable practice of modifying the kernel API, it is no longer possible to make simple changes to support different kernels. Accordingly, I am no longer supporting ay Ubuntu setups. Sorry, but I was wasting too much time.

**Comment by lsannin** [comment] 2015-04-09 18:57
OMG!!, thanks a lot anyway

**Comment by TuciHU** [comment] 2015-05-02 21:39
Thank you. 
https://github.com/troy-tan/driver_store/tree/master/bluetooth/8723BE works fine on Lenovo Flex2 laptop running Mint 17.1 Cinnamon 64 bit. 0bda:b728 internal BT.

**Comment by lwfinger** [comment] 2015-05-03 01:49
Are you saying that the kernel branch of http://github.com/lwfinger/rtl8723au_bt.git does not work with that Lenovo laptop?

**Comment by rzr** [comment] 2015-05-03 21:42
Is there a more up to date branch for 4.1.0-rc1+ ? if not some ports efforts will be needed ie:

  rtl8723au_bt/btusb.c:114:12: error: ‘struct hci_dev’ has no member named ‘reassembly’


What is the plan for kernel mainline integration ?

**Comment by lwfinger** [comment] 2015-05-04 16:06
New kernels will build *ONLY* with the kernel branch. Switch to that and you will be fine. You should have been using it anyway.

The updated driver has been submitted to and accepted by the Bluetooth driver group. It should have been in 4.1, but there were some delays. I expect it in 4.2.

**Comment by rzr** [comment] 2015-05-04 17:40
Yea I got it working and documented a bit on my laptop note page , 
may it save time for others, I can improve it if needed .. 

http://rzr.online.fr/q/ideapad

Thanks again I'll track the upstream integration ...

Btw is there a test suite to test reliability of wifi / bluetooth ?

**Comment by TuciHU** [comment] 2015-05-07 18:34
Hi,

sorry for the late answer.
The whole story:
I installed http://github.com/lwfinger/rtl8723au_bt.git 
<https://github.com/lwfinger/rtl8723au_bt.git> the new branch in 
February. It did not work at all.

Last week I had time and made an attempt with 
https://github.com/troy-tan/driver_store/tree/master/bluetooth/8723BE. 
For first sight it worked fine. BT device could be paired which did not 
happen before. But a few days later it was proved unstable. That means 
it works only if AC power is plugged at boot. I think it is rather 
mysterious.
So I uninstalled rtk_btusb driver and I installed the *master branch of 
**http://github.com/lwfinger/rtl8723au_bt.git 
<https://github.com/lwfinger/rtl8723au_bt.git>**this week. This driver 
reproduces the same faults (dependency on AC power) as 
**http://github.com/lwfinger/rtl8723au_bt.git 
<https://github.com/lwfinger/rtl8723au_bt.git>**did.*

I'm going to test the *kerner branch **of 
**http://github.com/lwfinger/rtl8723au_bt.git 
<https://github.com/lwfinger/rtl8723au_bt.git>* as you suggested it. On 
other hand the realtek wifi is also unstable. I'm going to test also the 
https://github.com/lwfinger/rtlwifi_new. I could only hope that together 
the http://github.com/lwfinger/rtl8723au_bt.git 
<https://github.com/lwfinger/rtl8723au_bt.git> and the 
https://github.com/lwfinger/rtlwifi_new  will work correctly.

If I can help you with further details pls let me know.

br.,

-- 
----
Bertók Attila
mailto:kondu12@citromail.hu
+36-30-9413-500

2015-05-03 03:49 keltezéssel, lwfinger írta:

**Comment by louisvd** [comment] 2015-05-29 14:39
Hi

I have a Lenovo Thinkpad E540 with the famed 0bda:b728 Realtek Bluetooth built-in device co-operating with the RTL8723BE PCIe Wireless Network Adapter.

The device appears to be "working" and when I open the Gnome control panel I can disable and enable it (as shown in the logs), and it shows that it is scanning for devices -- but it does not find any devices (other computers or my cell phone) and I cannot find it with my cell phone.

Yesterday kernel 4.0.4 was released on Fedora 21, and with renewed hope in my eye tried it with my Bluetooth device.  Sadly, still no luck.  The same holds true for the Fedora 22 Beta 3 live DVD.

I just downloaded and "make ; make install" the current lwfinger/rtlwifi_new files, which installed successfully, but still made no change to my bluetooth woes.  

Is there ANYTHING else I can do, or any info I can provide you.  I am willing to test and help to get this solved.

Below some info in the meantime:

##With the original RPM included files:
[root@lenovo ~]# modinfo btcoexist
filename:       /lib/modules/4.0.4-201.fc21.x86_64/kernel/drivers/net/wireless/rtlwifi/btcoexist/btcoexist.ko.xz
description:    Realtek 802.11n PCI wireless core
license:        GPL
author:         Larry Finger	<Larry.FInger@lwfinger.net>
author:         Realtek WlanFAE	<wlanfae@realtek.com>
author:         Page He	<page_he@realsil.com.cn>
depends:        
intree:         Y
vermagic:       4.0.4-201.fc21.x86_64 SMP mod_unload 
signer:         Fedora kernel signing key
sig_key:        82:3D:05:8E:7B:B9:D6:1F:E3:12:EA:50:91:0D:84:3C:09:37:CF:DB
sig_hashalgo:   sha256

##With the newly compiled modules from lwfinger/rtlwifi_new:
[root@lenovo rtlwifi_new-master]# modinfo btcoexist
filename:       /lib/modules/4.0.4-201.fc21.x86_64/kernel/drivers/net/wireless/rtlwifi/btcoexist/btcoexist.ko.xz
description:    Realtek 802.11n PCI wireless core
license:        GPL
author:         Larry Finger	<Larry.FInger@lwfinger.net>
author:         Realtek WlanFAE	<wlanfae@realtek.com>
author:         Page He	<page_he@realsil.com.cn>
depends:        rtlwifi
vermagic:       4.0.4-201.fc21.x86_64 SMP mod_unload 

Other information:
[root@lenovo rtlwifi_new-master]# hciconfig -a
hci0:	Type: BR/EDR  Bus: USB
	BD Address: 48:D2:24:FA:5E:5C  ACL MTU: 820:8  SCO MTU: 255:16
	UP RUNNING PSCAN ISCAN 
	RX bytes:6444 acl:0 sco:0 events:1001 errors:0
	TX bytes:6929 acl:0 sco:0 commands:843 errors:0
	Features: 0xff 0xff 0xff 0xfe 0xdb 0xff 0x7b 0x87
	Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
	Link policy: RSWITCH HOLD SNIFF PARK 
	Link mode: SLAVE ACCEPT 
	Name: 'lenovo.localdomain'
	Class: 0x1c010c
	Service Classes: Rendering, Capturing, Object Transfer
	Device Class: Computer, Laptop
	HCI Version: 4.0 (0x6)  Revision: 0xb
	LMP Version: 4.0 (0x6)  Subversion: 0x8723
	Manufacturer: Realtek Semiconductor Corporation (93)

[root@lenovo ~]# lsusb
Bus 004 Device 002: ID 8087:8000 Intel Corp. 
Bus 004 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 8087:8008 Intel Corp. 
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 0bdb:193e Ericsson Business Mobile Networks BV 
Bus 001 Device 007: ID 0bda:b728 Realtek Semiconductor Corp. 
Bus 001 Device 002: ID 046d:c52e Logitech, Inc. MK260 Wireless Combo Receiver
Bus 001 Device 006: ID 0bda:5719 Realtek Semiconductor Corp. 
Bus 001 Device 005: ID 138a:0011 Validity Sensors, Inc. VFS5011 Fingerprint Reader
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

[root@lenovo rtlwifi_new-master]# lsmod | grep -iE "bt|rtl"
ebtable_nat            16384  0 
ebtable_broute         16384  0 
bridge                114688  1 ebtable_broute
ebtable_filter         16384  0 
ebtables               32768  3 ebtable_broute,ebtable_nat,ebtable_filter
btusb                  45056  0 
bluetooth             503808  32 bnep,btusb,rfcomm
rtl8723be              90112  0 
btcoexist              53248  1 rtl8723be
rtl8723_common         24576  1 rtl8723be
rtl_pci                28672  1 rtl8723be
rtlwifi                73728  2 rtl_pci,rtl8723be
mac80211              708608  3 rtl_pci,rtlwifi,rtl8723be
cfg80211              552960  2 mac80211,rtlwifi

[root@lenovo rtlwifi_new-master]# rpm -qa | grep -i blue | sort
bluez-5.29-2.fc21.x86_64
bluez-cups-5.29-2.fc21.x86_64
bluez-libs-5.29-2.fc21.x86_64
gnome-bluetooth-3.14.1-1.fc21.x86_64
gnome-bluetooth-libs-3.14.1-1.fc21.x86_64
NetworkManager-bluetooth-0.9.10.2-5.fc21.x86_64
pulseaudio-module-bluetooth-6.0-2.fc21.1.x86_64

[root@lenovo rtlwifi_new-master]# rpm -qa | grep -i kernel | sort
abrt-addon-kerneloops-2.3.0-4.fc21.x86_64
kernel-3.19.5-200.fc21.x86_64
kernel-3.19.7-200.fc21.x86_64
kernel-4.0.4-201.fc21.x86_64
kernel-core-3.19.5-200.fc21.x86_64
kernel-core-3.19.7-200.fc21.x86_64
kernel-core-4.0.4-201.fc21.x86_64
kernel-devel-3.19.5-200.fc21.x86_64
kernel-devel-3.19.7-200.fc21.x86_64
kernel-devel-4.0.4-201.fc21.x86_64
kernel-headers-4.0.4-201.fc21.x86_64
kernel-modules-3.19.5-200.fc21.x86_64
kernel-modules-3.19.7-200.fc21.x86_64
kernel-modules-4.0.4-201.fc21.x86_64
kernel-modules-extra-3.19.5-200.fc21.x86_64
kernel-modules-extra-3.19.7-200.fc21.x86_64
kernel-modules-extra-4.0.4-201.fc21.x86_64
libreport-plugin-kerneloops-2.3.0-6.fc21.x86_64

Info extracted from dmesg:
[    3.456883] usb 1-7: new full-speed USB device number 3 using xhci_hcd
[    3.621394] usb 1-7: No LPM exit latency info found, disabling LPM.
[    3.622387] usb 1-7: New USB device found, idVendor=0bda, idProduct=b728
[    3.622389] usb 1-7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.622390] usb 1-7: Product: Bluetooth Radio
[    3.622391] usb 1-7: Manufacturer: Realtek
[    3.622393] usb 1-7: SerialNumber: 00e04c000001

[   29.094775] Bluetooth: Core ver 2.20
[   29.094791] Bluetooth: HCI device and connection manager initialized
[   29.094794] Bluetooth: HCI socket layer initialized
[   29.094797] Bluetooth: L2CAP socket layer initialized
[   29.094801] Bluetooth: SCO socket layer initialized
[   37.562377] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   37.562380] Bluetooth: BNEP filters: protocol multicast
[   37.562384] Bluetooth: BNEP socket layer initialized
[   97.125045] Bluetooth: RFCOMM TTY layer initialized
[   97.125051] Bluetooth: RFCOMM socket layer initialized
[   97.125119] Bluetooth: RFCOMM ver 1.11

**Comment by lwfinger** [comment] 2015-05-29 15:56
You failed to say what branch you are using, but I think you are using "master". The "kernel" branch is the one you should be using.

**Comment by louisvd** [comment] 2015-06-02 11:15
You are correct!  And sorry about that.  Yes, I was using the master branch.  

Last night kernel-4.0.4-202.fc21.x86_64 was released for Fedora 21, so after installing that, I downloaded your kernel branch driver and ran: make ; make install

I rebooted just to be sure, but I still have exactly the same problem as with the drivers in the supplied kernel -- namely that the laptop doesn't find any bluetooth devices, and my phone cannot find the laptop.

Besides the Gnome tool - which just has an on and off slider - what else can I use to test the BT functionality?

What other info can I give you that may help you to help me in turn?

Thanks!!

**Comment by lwfinger** [comment] 2015-06-02 14:51
The first thing to check is what does the dmesg output show. Secondly, as, as with any USB device, is the USB ID as shown by the lsusb command.

**Comment by 9behem6** [comment] 2015-06-11 11:07
Hello everyone!

@louisvd 
Hello, I have Fedora 21 too with 4.0.4 kernel. Some investigation led me to understanding that built module does not replace the current one. Additionally (according to Fedora's new kernels) all modules are xzipped (btusb.ko.xz) and after 'make install' new module (btusb.ko) is placed to modules structure in uncompressed mode... 'modprobe' command uses the compressed one. When I manually replaced original BT driver with new one (I've compressed it earlier) the system did not allow to load it. The reason for me is in Secure mode enabled by UEFI. Solution has two ways: the simplest but not secure - just disable secure mode in UEFI menu (this requires setting supervisor password, Google knows it :) ) or - create your own key, sign the module file, xzip it and place your created key to UEFI shim repo.

Hope, this will help.

**Comment by birarda** [comment] 2015-07-02 06:05
Having similar issues to others here but with RTL8821AE. Here is the output of lsusb:

```
$ lsusb
Bus 002 Device 002: ID 8087:8001 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8009 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 0bda:0821 Realtek Semiconductor Corp. 
Bus 003 Device 002: ID 046d:c52b Logitech, Inc. Unifying Receiver
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Basically the device is recognized and shows up via hciconfig/hcitool but whenever I scan for devices I get nothing. Is this a driver issue I can easily solve or should I just be grabbing a bluetooth dongle since there isn't support for this card yet?

**Comment by troy-tan** [comment] 2015-07-02 06:11
@birarda 
Have you installed the bluetooth driver here?
https://github.com/troy-tan/driver_store/tree/master/bluetooth/8821AE

**Comment by birarda** [comment] 2015-07-02 06:22
@troy-tan trying that now I get 
`Linux_BT_USB_2.10.20140212_Azurewave/blutooth_usb_driver/rtk_btusb.c:149:3: error: implicit declaration of function ‘hci_recv_fragment`

while running `sudo make install`

**Comment by troy-tan** [comment] 2015-07-02 06:57
I cannot access github via terminal right now, please try this new driver:
https://onedrive.live.com/redir?resid=E882B17064B6FCD9!567&authkey=!AHipazEQtX-WE08&ithint=file%2crar

**Comment by lwfinger** [comment] 2015-07-02 15:37
I cannot help with troy-tan's code, but there is a report that the Bluetooth driver in http://github.com/lwfinger/rtl8723au_bt.git fails on Ubuntu releases - even 15.04 - because their version of Bluez is too old. My system uses Bluez V5.23, and it works fine with RTL8821AE. If you do have a new enough version of Bluez and it still does not work, then please open a new issue in that other repo. The resolution might be of interest to other BT users, and it would be hard to find here.

**Closed by lwfinger** 2015-07-02 15:37 UTC
