### ISSUE TITLE
Weak wifi signal on kali linux Realtek RTL8723BE

### ISSUE THREAD

**Issue by chembai** [lwfinger/rtlwifi_new#102] opened 2016-03-14 19:53 UTC
hi guys,im a newbie to kali linux,i installed it on my hp device which has Realtek RTL8723be chipset
when i boot my system my monitor gets filled with error (like pcie bus error,cant find device with id00e5).
My wifi signal is so low that it doesnt show when i go to next room.

my dmesg log:-
[ 1339.326199] pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
[ 1339.326575] pcieport 0000:00:1c.5: can't find device of ID00e5
[ 1339.326593] pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
[ 1339.326616] pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
[ 1339.326623] pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00000000
[ 1339.326629] pcieport 0000:00:1c.5:    [ 0] Receiver Error         (First)
[ 1339.326640] pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
[ 1339.327287] pcieport 0000:00:1c.5: can't find device of ID00e5
[ 1339.429264] pcieport 0000:00:1c.5: AER: Corrected error received: id=00e5
[ 1339.429287] pcieport 0000:00:1c.5: PCIe Bus Error: severity=Corrected, type=Physical Layer, id=00e5(Receiver ID)
[ 1339.429297] pcieport 0000:00:1c.5:   device [8086:9d15] error status/mask=00000001/00000000
[ 1339.429305] pcieport 0000:00:1c.5:    [ 0] Receiver Error         (First)

**Comment by lwfinger** [comment] 2016-03-14 20:58
Those bus errors are a problem with your hardware, or some other part of the software. I have never seen any low-signal strength issues cause bus errors. Please post the output of 'lspci -nn' so we can tell what device is on bus 1c:5.

**Comment by chembai** [comment] 2016-03-14 21:06
here is the lspci -nn output:-
00:00.0 Host bridge [0600]: Intel Corporation Sky Lake Host Bridge/DRAM Registers [8086:1904] (rev 08)
00:02.0 VGA compatible controller [0300]: Intel Corporation Sky Lake Integrated Graphics [8086:1916] (rev 07)
00:04.0 Signal processing controller [1180]: Intel Corporation Device [8086:1903] (rev 08)
00:14.0 USB controller [0c03]: Intel Corporation Device [8086:9d2f] (rev 21)
00:14.2 Signal processing controller [1180]: Intel Corporation Device [8086:9d31] (rev 21)
00:16.0 Communication controller [0780]: Intel Corporation Device [8086:9d3a] (rev 21)
00:17.0 SATA controller [0106]: Intel Corporation Device [8086:9d03] (rev 21)
00:1c.0 PCI bridge [0604]: Intel Corporation Device [8086:9d10] (rev f1)
00:1c.4 PCI bridge [0604]: Intel Corporation Device [8086:9d14] (rev f1)
00:1c.5 PCI bridge [0604]: Intel Corporation Device [8086:9d15] (rev f1)
00:1d.0 PCI bridge [0604]: Intel Corporation Device [8086:9d18] (rev f1)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:9d48] (rev 21)
00:1f.2 Memory controller [0580]: Intel Corporation Device [8086:9d21] (rev 21)
00:1f.3 Audio device [0403]: Intel Corporation Device [8086:9d70] (rev 21)
00:1f.4 SMBus [0c05]: Intel Corporation Device [8086:9d23] (rev 21)
01:00.0 3D controller [0302]: NVIDIA Corporation GM108M [GeForce 940M] [10de:1347] (rev a2)
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. Device [10ec:522a] (rev 01)
03:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter [10ec:b723]
04:00.0 Ethernet controller [0200]: Realtek Semiconductor Co., Ltd. RTL8101E/RTL8102E PCI Express Fast Ethernet controller [10ec:8136] (rev 0a)

**Comment by chembai** [comment] 2016-03-14 21:26
will installing kali linux 2.0 solve all these problems?(wifi connection,wifi detection,weak signal......)

**Comment by lwfinger** [comment] 2016-03-14 21:31
Bus 0:1c:5 is a PCI bridge. Note that the RTL8723BE is bus 3:00.0 and is probably connected to the third PCI bridge.

I have no idea is using Kali 2.0 will help or not. I have no experience with any Kali release.

**Comment by chembai** [comment] 2016-03-14 21:49
Ok can u pls tell me how to use the rock.new_btcoex branch 
Step by step installation.....

**Comment by izbushka** [comment] 2016-03-15 06:06
> Step by step installation.....
git clone https://github.com/lwfinger/rtlwifi_new.git
cd rtlwifi_new
git checkout rock.new_btcoex
make install

**Comment by lwfinger** [comment] 2016-03-15 06:13
Slight correction. Do not do the entire operation as root, but as a normal user. Then after the git checkout command,

make
sudo make install

**Comment by chembai** [comment] 2016-03-15 12:21
sorry lwfinger i dint get u.....

**Comment by chembai** [comment] 2016-03-15 14:08
when i try to install linux headers i get errors....

i tried to install linux headers by running the code:-
sudo apt-get install linux-headers-$(uname -r)

Following is the output:-

Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-headers-4.3.0-kali1-amd64
E: Couldn't find any package by glob 'linux-headers-4.3.0-kali1-amd64'
E: Couldn't find any package by regex 'linux-headers-4.3.0-kali1-amd64'

**Comment by chembai** [comment] 2016-03-15 19:33
izbushka bu im not able to run 'make' command in kali linux.....

Im getting following error:-

make -C /lib/modules/4.3.0-kali1-amd64/build:No such file or directory.stopMakefile:58: recipe for target 'all' failed
make: ***[all] Error 2

**Comment by chembai** [comment] 2016-03-16 03:04
i installed like izbushka  said but still im having weak wifi signal...
even when i sit near my wifi modem im oly getting signal strength :- ok
what should i do...

**Comment by chembai** [comment] 2016-03-16 03:14
And when i get out of the room the wifi is not even detected

**Comment by izbushka** [comment] 2016-03-16 06:14
**chembai**, you should add _ant_sel=2_ or _ant_sel=1_ to the module parameters:
_/etc/modprobe.d/rtl8723be.conf:_
`options rtl8723be ant_sel=2`
and probably play with  _ips=0 fwlps=0 swlps=0 msi=1_ also

**Comment by lwfinger** [comment] 2016-03-16 16:10
Do not change msi UNLESS you are having problems with interrupts and are never seeing any action from the interface. In this case, that is definitely not true. I would suggest "ips=0 ant_sel=1".

**Comment by chembai** [comment] 2016-03-17 18:05
still my signal strength is ok and im not able to access wifi when im not near my wifi modem. :(

**Comment by lwfinger** [comment] 2016-03-17 18:35
Please post signal strengths for when you can connect, and when you cannot.

**Comment by chembai** [comment] 2016-03-18 18:13
this is when i cannot connect to wifi:-
wlan0     IEEE 802.11bgn  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:off

**Comment by chembai** [comment] 2016-03-18 18:18
this is when i can connect to my wifi:-

![new](https://cloud.githubusercontent.com/assets/13054251/13887814/d0fd3064-ed63-11e5-9ea6-d8618c4437a6.png)

**Comment by lwfinger** [comment] 2016-03-18 19:02
These show me very little, but it certainly looks as if you do not have the correct antenna selected! For both good and bad cases, please post the output of

sudo iw dev wlp2s0 scan | grep signal

**Comment by chembai** [comment] 2016-03-18 19:36
sir it dsnt show anything.....

**Comment by lwfinger** [comment] 2016-03-18 19:55
Sorry about the wlp2s0 part. That is what I need to use. You should have used wlan0.

You have not gotten the ant_sel part done correctly. Please write down exactly what you have done.

**Comment by chembai** [comment] 2016-03-18 20:04
in my /etc/modprobe.d/rtl8723be.conf i have written the following things:-

'options rtl8723be ips=0 ant_sel=1'

**Comment by lwfinger** [comment] 2016-03-18 20:07
What does 'dmesg | grep ant_sel' show?

**Comment by chembai** [comment] 2016-03-18 20:08
nothing:(

**Comment by chembai** [comment] 2016-03-18 20:09
![screenshot from 2016-03-19 01-38-43](https://cloud.githubusercontent.com/assets/13054251/13890797/580b944c-ed73-11e5-83b3-81b876e68550.png)

**Comment by chembai** [comment] 2016-03-18 20:26
sir sorry when i give sudo wlan0 scan | grep signal i get :-

signal: -78.00 dBm

**Comment by lwfinger** [comment] 2016-03-18 20:50
That signal is way too small. The lack of output from the 'dmesg | grep ant_sel' command means that you have installed the correct driver. Have you tried ant_sel=2? We told you to use 1 as that is usually correct. If you do not get signals of approximately -40 dBm when close to the AP with one of those 3 values, then there is something else wrong.

Is your machine accessible from the outside world via ssh?

**Comment by chembai** [comment] 2016-03-19 15:45
@lwfinger i dont think its is accessible...

after giving the ant_sel=2 my wifi dosent show any available networks :(

**Comment by lwfinger** [comment] 2016-03-19 16:26
If ant_sel=1 and ant_sel=2 both fail, then you have a different problem. You already tried ant_sel=0 with the original code.

Have you checked inside to make sure that there are any antennas connected to the card?

**Comment by chembai** [comment] 2016-03-20 18:59
@lwfinger no sir i havnt... 
is there any other fix for this issue?? 
should i try any other branch than rock.new_btcoex??

**Comment by lwfinger** [comment] 2016-03-20 19:20
As I have said before, you have a different problem. Any branch of rtlwifi_new now has the fix for the antenna connected to the wrong connector, but THAT IS NOT YOUR PROBLEM!

Why do you almost never answer my questions? Until you are very careful to do that, I will not respond to you.

**Comment by chembai** [comment] 2016-03-20 19:34
Extremely sorry sir....

**Comment by chembai** [comment] 2016-03-22 18:06
sir I have one doubt, if my antennas are not connected I cant get access to wifi in my windows 10 also ryt?? if so that is not my problem as my wifi works fine in windows 10.... I can easily access my wifi with good signal strength for like 5meters or higher

**Comment by chembai** [comment] 2016-03-22 19:49
sir when i executed :- 
sudo modprobe -rv rtl8723be
and
sudo modprobe -v rtl8723be ant_sel=2
i get excellent wifi strength, but i cannot connect my system to wifi.....

**Comment by chembai** [comment] 2016-03-23 05:26
hey @lwfinger pls help me here i think im close fixing the error......

btw i think i have answered all ur qns...if not (im really sorry)....

**Comment by lwfinger** [comment] 2016-03-23 19:36
OK. I'll give you one more try.

Do exactly the following from the directory that you have cloned from GitHub (probably rtlwifi_new):
git checkout rock.new_btcoex
git pull
make
sudo make install

Now run the following and post your results:

sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=0
sudo iw dev wlan0 scan | grep signal
sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=1
sudo iw dev wlan0 scan | grep signal

**Comment by chembai** [comment] 2016-03-23 22:01
After executing ant_sel =0 my signal strength is 
Signal : -68.00dBm
Signal:  -73.00dBm

After executing ant_sel=1 my signal strength is
Signal: -66.00 dBm
Signal: -74.00dBm

**Comment by chembai** [comment] 2016-03-23 22:02
Strange thing is that in both the cases i cannot connect to my wifi......

**Comment by lwfinger** [comment] 2016-03-23 23:51
I wanted to see the output of the modprobe commands.

That strength is way too low to connect reliably. You need more like -50 dBm, which is roughly 10,000 times stronger.

**Comment by chembai** [comment] 2016-03-24 09:17
root@kali:~# sudo modprobe -rv rtl8723be
libkmod: ERROR ../libkmod/libkmod-config.c:635 kmod_config_parse: /etc/modprobe.d/rtl8723be.conf line 1: ignoring bad line starting with '`options'
rmmod rtl8723be
rmmod rtl_pci
rmmod btcoexist
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211

**Comment by chembai** [comment] 2016-03-24 09:18
root@kali:~# sudo modprobe -v rtl8723be ant_sel=0
libkmod: ERROR ../libkmod/libkmod-config.c:635 kmod_config_parse: /etc/modprobe.d/rtl8723be.conf line 1: ignoring bad line starting with '`options'
insmod /lib/modules/4.4.0-kali1-amd64/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko fwlps=N ips=N ant_sel=0

**Comment by chembai** [comment] 2016-03-24 09:19
root@kali:~# sudo modprobe -v rtl8723be ant_sel=1
libkmod: ERROR ../libkmod/libkmod-config.c:635 kmod_config_parse: /etc/modprobe.d/rtl8723be.conf line 1: ignoring bad line starting with '`options'
insmod /lib/modules/4.4.0-kali1-amd64/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.4.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko fwlps=N ips=N ant_sel=1

**Comment by Bharat-Kalluri** [comment] 2016-03-24 10:22
> 1: ignoring bad line starting with '`options'

I think the line in the /etc/modprobe.d/rtl8723be.conf  file is being ignored because of the 

> '

symbol it has before it

**Comment by lwfinger** [comment] 2016-03-24 13:48
Please delete that file and retry again. This is the kind of problem that goes undetected when you are not posting all the input. I want the only options added to be the one on the command line.

**Comment by chembai** [comment] 2016-03-26 08:47
sir i deleted that file and ran those codes... 
i executed ant_sel=2 ,now my wifi signal is -34.00dbBm bt still my system is not connecting to wifi....

**Comment by lwfinger** [comment] 2016-03-26 16:18
If you have that signal strength, the problem is not the driver. As I do not run Kali Linux, I cannot help you with your user space wireless routines; however, I am 99.5% sure that is where the problem lies. Good Luck.

**Closed by lwfinger** 2016-03-26 16:18 UTC

**Comment by progracks** [comment] 2017-03-31 04:51
thanks brothers you're discussion gave me much knowledge and i fix my wireless card issue

**Comment by monto555** [comment] 2017-07-21 07:11
i have exactly the same problem . Help!

**Comment by SSSzone** [comment] 2017-08-20 09:16
sir iwfinger..thanks..u solved my weak wifi signal problem by ant_sel=1

**Comment by frostshawn28** [comment] 2018-02-05 12:47
I also had the same problem. But after running the following commands, the wifi is working fine.

```
sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=2
```

**Comment by lwfinger** [comment] 2018-02-05 17:40
Are you aware that your "fix" will not survive a reboot? To do that, you will need to create a suitable file in /etc/modprobe.d/. How to do that is left as an exercise. It is well documented, both in this repo and elsewhere.

**Comment by frostshawn28** [comment] 2018-02-08 12:07
Yes sir, I’m aware of that. But is the way to make this effect permanent?

**Comment by lwfinger** [comment] 2018-02-08 17:40
This topic has been covered many times, but here it is again.

As root, use your favorite editor to create a file named /etc/modprobe.d/50-rtl8723be.conf. That file should consist of a single line containing "options rtl8723be ant_sel=2". Do not include the quotation marks.

**Comment by BackSpoofer** [comment] 2018-04-17 18:02
Help please...
I installed wifi drivers of the same wireless card as u mentioned above in kali Linux. But when i run windows 10 there is no wifi detecting even the drivers are installed...(Actually kali Linux 2018 and windows 10 are dual Booted in my ho laptop)

Please help me...

**Comment by lwfinger** [comment] 2018-07-30 14:45
Let me repeat again: BU != BE!!!!!! In other words, USB != PCIe. The ant_sel option was added to the driver for the RTL8723BE because some vendors saved a few pennies by including only one antenna, but encoded the EFUSE with the wrong value for the connector they actually used. To my knowledge, every RTL8723BU has been correctly built with two antennas, thus the rtw_ant_num value should not matter.

To change my mind, you will need to demonstrate that the wireless signal strength is different when the value of the parameter is changed.

**Comment by cypa** [comment] 2018-07-30 15:34
I've got Prestigio 133S with BU.
A few months it worked good, but a yesterday WiFi lost connections and wifi-menu given no scan results. So I've searched inet for help and found this thread. After adding rtw_ant_num=1 WiFi connected again.

Now I've check with rtw_ant_num=1 and rtw_ant_num=0 all works same, but without the parameter  no rtw_ant_num signals slightly better.

I'm confused - why is the failure appeared after all? After poweroff WiFi works fine again, strange!

**Comment by lwfinger** [comment] 2018-07-30 17:45
What did you update when the failure started?
Where are you getting a driver? Certainly, it is not from this repo, which does not include a driver for this USB device.

**Comment by Sulistyarif** [comment] 2018-11-07 14:11
> This topic has been covered many times, but here it is again.
> 
> As root, use your favorite editor to create a file named /etc/modprobe.d/50-rtl8723be.conf. That file should consist of a single line containing "options rtl8723be ant_sel=2". Do not include the quotation marks.

i have done this step, and do echo "options..........." step, but wifi will be weak again on every restrating my HP laptop, and my solution is make .sh file that when i run the the .sh file, will run below  line of command :

cd rtlwifi_new/
make clean && make
sudo make install
sudo modprobe -r rtl8723be
sudo modprobe rtl8723be
sleep 5
sudo modprobe -r rtl8723be
sudo modprobe rtl8723be ant_sel=2
iwlist scan | egrep -i 'ssid|quality'

run it with sudo and my wifi will strong again.. hahaha
maybe somebody have easier step ?

**Comment by lwfinger** [comment] 2018-11-07 14:42
It looks as if you did not make the file in /etc/modprobe.d correctly. Please do the following:

sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be

and post the console output from those two lines.

Note that everything in your script down to the "sleep" line essentially does nothing other than to remake the driver if the kernel changes. Only the unload/reload does anything, and that has the option done correctly. Incidentally, you are fortunate that a hot reload actually works. On many systems, an antenna selection change requires a power-off step.

**Comment by Sulistyarif** [comment] 2018-11-07 22:58
> It looks as if you did not make the file in /etc/modprobe.d correctly. Please do the following:
> 
> sudo modprobe -rv rtl8723be
> sudo modprobe -v rtl8723be
> 
> and post the console output from those two lines.
> 
> Note that everything in your script down to the "sleep" line essentially does nothing other than to remake the driver if the kernel changes. Only the unload/reload does anything, and that has the option done correctly. Incidentally, you are fortunate that a hot reload actually works. On many systems, an antenna selection change requires a power-off step.




sudo modprobe -rv rtl8723be
[sudo] password for sulistyarif: 
rmmod rtl8723be
rmmod rtl_pci
rmmod rtl8723_common
rmmod btcoexist
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211

sudo modprobe -v rtl8723be
insmod /lib/modules/4.15.0-38-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.15.0-38-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.15.0-38-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.15.0-38-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.15.0-38-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko 
insmod /lib/modules/4.15.0-38-generic/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.15.0-38-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko ant_sel=2 ant_sel=2 ant_sel=1 

like this ?

**Comment by Sulistyarif** [comment] 2018-11-09 05:30
> Notice that you are setting ant_sel 3 times, but only the last one is effective, thus you are setting ant_sel=1. You have screwed up the files in /etc/modprobe.d/. You can find the faulty places by the following command:
> 
> grep -r ant_sel /etc/modprobe.d/

i have 3 different file rtl8723; 50-rtl8723be.conf, rtl8723-ant-sel.conf, and rtl8723be.conf
this is when i grep it one by one :

grep ant_sel /etc/modprobe.d/50-rtl8723be.conf 
options rtl8723be ant_sel=2

grep ant_sel /etc/modprobe.d/rtl8723-ant-sel.conf 
options rtl8723be ant_sel=2

grep ant_sel /etc/modprobe.d/rtl8723be.conf 
options rtl8723be ant_sel=1

is this three difference configuration file make the uneffective ?

**Comment by lwfinger** [comment] 2018-11-09 06:05
Yes. You need to delete /etc/modprobe.d/rtl8723be.conf and /etc/modprobe.d/rtl8723-ant-sel.conf. Once you do that, I'm certain that your system will come up correctly with no other commands needed.

The name of the file is important only in that the files are processed in alphabetic order. Normally, on uses the "50-" prefix in case there are files that must be processed before any of the module load options.

**Comment by Sulistyarif** [comment] 2018-11-09 10:50
Thank you very very very much, its fixed now.. hahaha

But it works well on ant_sel=2

nice @lwfinger :+1:

**Comment by socialism7** [comment] 2020-01-21 10:06
I try

> sudo modprobe -r rtl8723de && sudo modprobe rtl8723de ant_sel=3

but, how to make it's permanently?

**Comment by lwfinger** [comment] 2020-01-21 16:31
You need to create an options file in /etc/modprobe.d. I have described that action at least 50 times. Please do a bit of research.

Are you sure that "3" is the correct value? The program expects 0, 1, or 2.
