### ISSUE TITLE
Low speed on RTL8723BE

### ISSUE THREAD

**Issue by fireio** [lwfinger/rtlwifi_new#317] opened 2018-02-01 17:36 UTC
The download speed from my laptop's wifi Hotspot, reduced to ~ 100 KB/s. This seems to be from the recent kernel upgrade. I'm using 4.14.15-1-ARCH GNU/Linux and using NetworkManager to create hotspot. Is there anything else which I should add? (Device: RTL8723BE)

**Comment by shivamkakkar** [comment] 2018-02-01 17:52
Relevant dmesg: https://pb.gehidore.net/mdZa
Full dmesg: https://pastebin.ubuntu.com/26501749/

**Comment by lwfinger** [comment] 2018-02-01 19:03
Does file /lib/firmware/rtlwifi/rtl8723befw_36.bin exist? That is the firmware needed for this version of the driver.

**Comment by fireio** [comment] 2018-02-02 02:42
Yes, it exists. I found another file /lib/firmware/rtlwifi/rtl8723befw.bin, which might be related to this issue. Added both and attached:
[rtl_wifi_binaries.zip](https://github.com/lwfinger/rtlwifi_new/files/1687902/rtl_wifi_binaries.zip)

**Comment by fireio** [comment] 2018-02-03 11:02
I also tried the test (hosting wifi hotspot, and python SimpleHTTPServer, downloading 100 MB file from laptop to phone) in a different physical environment, so it's likely that the issue isn't due to too many WiFi devices.

**Comment by p-gmueller** [comment] 2018-02-07 20:32
I Have the same problem. Since one of the last updates I have poor speedrate up to 500kb/s.

**Comment by lwfinger** [comment] 2018-02-07 20:37
Without actually measuring and reporting the signal strength, there is nothing I can do. At t minimum, you need to explore the various ant_sel values.

**Comment by p-gmueller** [comment] 2018-02-07 20:48
what do you need exactly? How can I build/measure such a report?

**Comment by p-gmueller** [comment] 2018-02-07 20:59
output of iwconfig 
wlp2s0    IEEE 802.11bgn  ESSID:"..."  
          Mode:Managed  Frequency:2.437 GHz  Access Point: 34:81:C4:F9:03:F1   
          Bit Rate=72.2 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:off
          Link Quality=70/70  Signal level=-26 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:3070   Missed beacon:0

**Comment by lwfinger** [comment] 2018-02-08 18:59
iwconfig is obsolete, and cannot be trusted for correct info. Use

sudo iw dev wlp2s0 scan | egrep "SSID|signal"

Post that output. If that signal of -26 dBm holds, that seems quite large. I have no idea at what signal, the amplifiers will overload. At 2 m from the AP, values of -35 dBm are typical.

**Comment by p-gmueller** [comment] 2018-02-08 20:29
Thats the output:
signal: -34.00 dBm
SSID: ...

**Comment by fireio** [comment] 2018-02-08 20:33
When hotspot is on:
command failed: Operation not supported (-95)

Otherwise output (SSID removed) :
	signal: -38.00 dBm
	signal: -64.00 dBm
	signal: -72.00 dBm
	signal: -66.00 dBm
	signal: -76.00 dBm
When hotspot is on the speed is really slow, same issue on my friend's laptop (RTL8723BE too)

**Comment by p-gmueller** [comment] 2018-02-08 20:39
When i use the standard driver i runs with good data rates, but only for very very short distances to the AP.  If I increase the distance to the AP to 0,8m the data rates break down very fast. Thats the issue why I used your driver for the last 2 years.

**Comment by fireio** [comment] 2018-02-08 20:42
Isn't the standard driver same as this driver in new kernel?

**Comment by p-gmueller** [comment] 2018-02-08 20:49
With standard driver I mean the default kernel driver.

**Comment by fireio** [comment] 2018-02-08 20:51
Yes, that's what I'm referring to. Isn't lwfinger/rtlwifi_new used in kernel for RTL8723BE?

**Comment by fireio** [comment] 2018-02-08 21:20
All values < 25 cm away from laptop, which is hosting. checked using WiFi Signal Strength meter in android.
ant_sel=2  : -85 dBm
ant_sel=1  : -26 dBm
ant_sel=0  : -34 dBm

**Comment by lwfinger** [comment] 2018-02-08 22:20
The driver in the master branch is older than the current kernel. The kernel_version branch is about the same, and the extended branch has parts that are newer than mainline.

@fireio: You need to use ant_sel=1. Are you slow speeds when you are using the RTL8723BE as an AP? Please describe the setup more carefully.

**Comment by fireio** [comment] 2018-02-09 02:43
Yes, I'm getting slow speeds if and only if I use it in AP mode. However in the normal mode (AP from android), I'm getting speeds of about 1880 kB/s, which is what I expect when I host AP from laptop. This used to work well until recently.

**Comment by lwfinger** [comment] 2018-02-09 20:21
If it used to work, please describe more thoroughly exactly what software was changed.

How are you establishing the AP? Is it the mini-AP employed by NetworkManager, or are you using something else?

**Comment by fireio** [comment] 2018-02-09 21:06
I'm using NetworkManager (https://pb.gehidore.net/QdDU). My friend tried with create_ap (probably https://wiki.archlinux.org/index.php/Software_access_point#create_ap, will confirm). We both faced the same issue. I can try creating hotspot with some other script if you'd like.

I'm of the opinion that a kernel update is likely the cause. It may not be the driver itself, but something within the kernel which affects the way driver operates. If you'd like me to try, I'll go back to a specific kernel version. I don't exactly remember when the issue first appeared. I'll try that one from archlinux PKGBUILD. Tomorrow, I'll try 4.12, if you don't respond with a specific version.

**Comment by fireio** [comment] 2018-02-10 23:18
I tried kernels by downloading from archive.archlinux.org. Didn't get fixed on linux-4.12.8-2-x86_64. But it worked perfectly fine on linux-4.10.13-1-x86_64. I was getting 1.8 MB/s on the laptop hotspot!

I'd like to know if it is possible and how to use 4.10.13's rtl8723be kernel module on 4.15.2
The next step should be to figure out if it's really rtl8723be driver which is the real cause.

**Comment by lwfinger** [comment] 2018-02-11 00:38
You need to bisect between 4.15 and 4.10. If you are unwilling to do the work, then I have no way to find the problem.

**Comment by fireio** [comment] 2018-02-11 12:00
Isn't it sufficient to bisect between 4.10 and 4.12, because it works in 4.12?
Without recompiling kernel: It works in 4.11.9 and fails in 4.12.0
I'll try bisection, but it'll take time, because I only have 2 core CPU.

**Comment by lwfinger** [comment] 2018-02-11 17:10
That should be enough as long as 4.11.0 works. You need a good one and a bad one at each end, but you cannot bisect between 4.12.0 and 4.11.9. They are in different series.

With a dual-core CPU, using -j5 on the make command will speed it up a lot.

**Comment by fireio** [comment] 2018-02-12 10:00
I'm already using -j5 and ccache. Last compile took 47 minutes. This is the current progress:
git bisect start
# good: [a351e9b9fc24e982ec2f0e76379a49826036da12] Linux 4.11
git bisect good a351e9b9fc24e982ec2f0e76379a49826036da12
# bad: [2ea659a9ef488125eb46da6eb571de5eae5c43f6] Linux 4.12-rc1
git bisect bad 2ea659a9ef488125eb46da6eb571de5eae5c43f6
# bad: [2ea659a9ef488125eb46da6eb571de5eae5c43f6] Linux 4.12-rc1
git bisect bad 2ea659a9ef488125eb46da6eb571de5eae5c43f6
# bad: [221656e7c4ce342b99c31eca96c1cbb6d1dce45f] Merge tag 'sound-4.12-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/tiwai/sound
git bisect bad 221656e7c4ce342b99c31eca96c1cbb6d1dce45f
# bad: [8d65b08debc7e62b2c6032d7fe7389d895b92cbc] Merge git://git.kernel.org/pub/scm/linux/kernel/git/davem/net-next
git bisect bad 8d65b08debc7e62b2c6032d7fe7389d895b92cbc
# bad: [cec381919818a9a0cb85600b3c82404bdd38cf36] Merge tag 'mac80211-next-for-davem-2017-04-28' of git://git.kernel.org/pub/scm/linux/kernel/git/jberg/mac80211-next
git bisect bad cec381919818a9a0cb85600b3c82404bdd38cf36
# good: [5cd8985a19090f2b0ce8700ae3ec19e06a4fc5e9] net-next: dsa: add Mediatek tag RX/TX handler
git bisect good 5cd8985a19090f2b0ce8700ae3ec19e06a4fc5e9
# bad: [763dbf6328e41de7a55851baf5ee49e367552531] net_sched: move the empty tp check from ->destroy() to ->delete()
git bisect bad 763dbf6328e41de7a55851baf5ee49e367552531
# bad: [24dcbf66220564cdb23129aa3854b49532b1a9d8] 6lowpan: Don't set IFF_NO_QUEUE
git bisect bad 24dcbf66220564cdb23129aa3854b49532b1a9d8

**Comment by fireio** [comment] 2018-02-12 16:12
Bisection done! 
`git bisect log` : https://pb.gehidore.net/BZLE

**Comment by fireio** [comment] 2018-02-12 17:01
I tried sudo rm /lib/firmware/rtlwifi/rtl8723befw_36.bin, and then rebooted (Normal 4.15.2 kernel)
And I was getting good speeds again.

**Comment by fireio** [comment] 2018-02-12 17:14
While testing, speeds went up to 4 MB/s. But now I'm getting nowhere close to that. The peak rate I observed over a 300 MB file was 1.7 MB/s. So the issue is bigger than firmware. I will repeat this test, this is the peak time in my timezone, so maybe it's due to a lot of WiFi devices.

But still, new firmware slows wifi devices quite significantly.

**Comment by lwfinger** [comment] 2018-02-12 20:09
Thanks for the bisection. I will send the Realtek engineers the news that the version 36 firmware causes a slowdown when the driver is set up as an AP.

Lots of factors can cause a file transfer slow down. I trust that the source file is on a local machine so that the WAN response and transfer rate is not involved.

**Comment by fireio** [comment] 2018-02-12 20:36
The file being transferred is on the laptop (Local machine). If you get any updates from them, please share here. If there are any issues reproducing the bug, I'll send more detailed information about my system.
Thanks for quick responses!

**Comment by p-gmueller** [comment] 2018-02-12 20:42
On my laptop I have Kubuntu 16.04. LTS with Kernel 4.4.0-112-generic, linux-firmware 1.157.15.
and rtlwifi-new-dkms 0.10. I run the adapter not in AP mode and it is also slow. What can I do to speed it up.

**Comment by fireio** [comment] 2018-02-12 20:52
Find where is your firmware located (rtl8723befw_36.bin). For me it's /lib/firmware/rtlwifi, delete this file from your system. Reboot. (and make sure you delete after every update). See change due to this commit to understand what's going on: https://patchwork.kernel.org/patch/9588675/.

**Comment by p-gmueller** [comment] 2018-02-12 21:03
I have deleted this file but this does not solvs the problem for my system.

**Comment by lwfinger** [comment] 2018-02-12 21:43
Do you have an HP laptop? If so, have you measured the signal strength with differing values of ant_sel?

Stating the dkms version does not tell us what software you are running. Which branch of rtlwifi_new?

**Comment by p-gmueller** [comment] 2018-02-12 21:56
Yes it is a HP. 
I have installed it with "sudo apt-get install rtlwifi-new-dkms linux-firmware"  
output is 
linux-firmware is already the newest version (1.157.15).
rtlwifi-new-dkms is already the newest version (0.10). 
I dont know of which branch the package is.

**Comment by lwfinger** [comment] 2018-02-12 22:18
If you are getting rtlwifi_new from Ubuntu, then I do not know what version or branch they have. You will need to learn that from them.

If you used git to clone this repo, then you can change directory to the one where the source is located and use 'git branch' to get the branch.

**Comment by lwfinger** [comment] 2018-02-12 22:31
extended

**Comment by p-gmueller** [comment] 2018-02-14 19:39
I hoppe I  build the module in the correct Version here is the output of: modinfo rtl8723be 

filename:       /lib/modules/4.4.0-112-generic/updates/dkms/rtl8723be.ko
firmware:       rtlwifi/rtl8723befw_36.bin
firmware:       rtlwifi/rtl8723befw.bin
description:    Realtek 8723BE 802.11n PCI wireless
license:        GPL
author:         Realtek WlanFAE <wlanfae@realtek.com>
author:         PageHe  <page_he@realsil.com.cn>
srcversion:     41E3D27D506CBEDC478A504
alias:          pci:v000010ECd0000B723sv*sd*bc*sc*i*
depends:        rtlwifi,rtl8723-common,rtl_pci,btcoexist,mac80211
vermagic:       4.4.0-112-generic SMP mod_unload modversions

The speed is good for short distances to the route. If I increase the distance the signal strength break down.

**Comment by p-gmueller** [comment] 2018-02-14 20:44
here some more information: the output for " sudo iw dev wlp2s0 scan | egrep "signal" " for ant_sel[0,1,2] is {-71.00 dBm, -72.00 dBm, -76.00 dBm}

**Comment by lwfinger** [comment] 2018-02-14 21:44
At 1.5m, you should have a signal of -30, or so. If ant_sel does not give a higher value for signal, you probably have NO antennas connected. You will need to open the laptop and check for missing connections.

**Comment by p-gmueller** [comment] 2018-02-14 21:51
This is not the problem with Windows 10 it runs perfectly.

**Comment by lwfinger** [comment] 2018-02-14 21:54
Are you sure you did the ant_sel test correctly? If you have an HP laptop, the Windows driver is tweaked to use the connected antenna even though the EFUSE is incorrectly coded.

**Comment by p-gmueller** [comment] 2018-02-14 22:13
I think I did the scan correct. First I changed ant_sel than I reboot the laptop and than I run the scan. I'm be sure that windows runs perfectly I have just tested it again.

**Comment by fireio** [comment] 2018-02-15 09:58
@p-gmueller, can you create AP from your laptop and then measure signal strengths from an android phone instead? I think that's what @lwfinger intends to ask.

**Comment by lwfinger** [comment] 2018-02-15 13:52
NO, you do not need to create an AP. Use the rtl8723be as a station.

When you reboot, you restore the default value for ALL the module parameters UNLESS you put that parameter into a .conf file in /etc/modprobe.d/.

Just do the following:
sudo modprobe -rv rtl8723be
sudo modprobe -v rtl8723be ant_sel=1
Connect to your AP, then
sudo iw dev wlp2s0 scan | egrep "SSID|signal"
Record the signal values, and repeat for ant_sel=2

**Comment by p-gmueller** [comment] 2018-02-15 18:59
in the last test I have set the ant_sel in /etc/modprobe.d/rtl8723be.conf
now i have deleted the ...conf file and here is the output:
user@HP-250-G4:~$ sudo modprobe -rv rtl8723be                  
rmmod rtl8723be
rmmod rtl_pci
rmmod rtl8723_common
rmmod btcoexist
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211
gmueller@HP-250-G4:~$ sudo modprobe -v rtl8723be ant_sel=1
insmod /lib/modules/4.4.0-112-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.4.0-112-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtlwifi.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtl_pci.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtl8723-common.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/btcoexist.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtl8723be.ko ant_sel=1
gmueller@HP-250-G4:~$ sudo iw dev wlp2s0 scan | egrep "SSID|signal"
        signal: -70.00 dBm
        SSID: ...
user@HP-250-G4:~$ sudo modprobe -rv rtl8723be
rmmod rtl8723be
rmmod rtl_pci
rmmod rtl8723_common
rmmod btcoexist
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211
gmueller@HP-250-G4:~$ sudo modprobe -v rtl8723be ant_sel=2
insmod /lib/modules/4.4.0-112-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.4.0-112-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtlwifi.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtl_pci.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtl8723-common.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/btcoexist.ko 
insmod /lib/modules/4.4.0-112-generic/updates/dkms/rtl8723be.ko ant_sel=2
gmueller@HP-250-G4:~$ sudo iw dev wlp2s0 scan | egrep "SSID|signal"
        signal: -69.00 dBm
        SSID: ...

should I run this again with debuglevel=...??

**Comment by p-gmueller** [comment] 2018-02-15 21:40
is this the solution for my problem???:
https://connectwww.com/how-to-solve-realtek-rtl8723be-weak-wifi-signal-problem-in-ubuntu/4625/

**Comment by p-gmueller** [comment] 2018-02-15 22:11
/var/log/kern.log contains a lot of the following messages:
kernel: [  280.002154] rtlwifi: IEEE80211_AMPDU_ERR!!!!:

**Comment by lwfinger** [comment] 2018-02-15 23:00
That Ubuntu link looks to to be what I have been telling you to do. As to setting debug options, I would not know what to debug. That is mainly for the Realtek experts.

That AMPDU_ERR indicates that you are getting a faulty ampdu action command from upstream. I have never seen that one.

Just to verify that the scans are looking at the correct device, pleas post the results for 'iw dev'.

**Comment by p-gmueller** [comment] 2018-02-15 23:10
iw dev
phy#0
        Interface wlp2s0
                ifindex 3
                wdev 0x1
                addr 44:1c:a8:07:df:d3
                type managed
                channel 6 (2437 MHz), width: 20 MHz, center1: 2437 MHz

**Comment by fireio** [comment] 2018-02-17 15:08
Did realtek guys reply? Can you please share it?

**Comment by lwfinger** [comment] 2018-02-17 17:41
They have other responsibilities that debugging your problem, which they cannot reproduce either. Please have some patience. I will let you know as soon as I get an answer.

**Comment by lwfinger** [comment] 2018-02-17 17:55
I just merged a patch that will log the action valu that leads to the AMPDU error. Please pull and run again with a version from this repo. Report the lines with the AMPDU error.

**Comment by p-gmueller** [comment] 2018-02-18 21:08
here is the log
[log.txt](https://github.com/lwfinger/rtlwifi_new/files/1735118/log.txt)

**Comment by lwfinger** [comment] 2018-02-19 00:45
You failed to pull the new version and use it. I still do not know what action was when the AMPDU_ERR was triggered.

**Comment by p-gmueller** [comment] 2018-02-19 10:16
sorry her is ne new log
[Log01.txt](https://github.com/lwfinger/rtlwifi_new/files/1736275/Log01.txt)

**Comment by lwfinger** [comment] 2018-02-19 17:13
The value of action is 1725971768, which is way out of bounds. Either it has not been initialized correctly, or it is being overwritten. The question remains as to why it only happens on your system?

I will see if I can set up a Kubuntu 16.04 system and try to duplicate your problem.

**Comment by lwfinger** [comment] 2018-02-20 20:24
I have now done the tests with Kubuntu 16.04. There is an ant_sel problem with rtl8723be in the extended branch. The master branch of this repo works fine. I never saw your AMPDU error.

You should use the instructions in https://fossbytes.com/install-upgrade-linux-kernel-ubuntu-mint-ukuu/ to install kernel 4.15.3. The ant_sel option works fine there.

**Comment by p-gmueller** [comment] 2018-02-21 09:14
Now I have tested  the master branch this works fine for the signal strength, but the data rate is very poor (download 350kbps, upload 10 kbps). 
I think the problem is the combination of the wifi version and the LTS Kernel 4.4.0-112-generic (I'm not sure what "112" means? is it the based on 4.12.). 
I can test it with mainline kernel, but why is the LTS kernel no longer supported by the RTL8723be?

**Comment by lwfinger** [comment] 2018-02-21 09:42
"112" means it is the 112th iteration of updates. It is based on kernel 4.4.

The RTL8723BE NIC was not well supported in kernel 4.4.0. That is the reason I told you to update to 4.15.3, where the support is much better.

**Comment by lwfinger** [comment] 2018-02-21 20:33
With 4.15.3, you should NOT be using this repo. Use the driver in the kernel!!!!!

**Comment by p-gmueller** [comment] 2018-02-21 22:35
Without repo it runs fine.

**Comment by biswaz** [comment] 2018-04-25 01:46
@p-gmueller Do you have a laptop with Intel/AMD Hybrid Graphics. I've the exact problem as yours and I saw somewhere it is related. I dont know if I'm correct.

I'm on Elementary OS Loki 0.4.1 with 4.4.0-121-generic

**Closed** 2020-07-06 19:49 UTC
