### ISSUE TITLE
RTL8188ce: frequent loss of connectivity, lts works

### ISSUE THREAD

**Issue by Soukyuu** [lwfinger/rtlwifi_new#203] opened 2017-01-14 17:18 UTC
I'm using the arch linux's rtlwifi_new-dkms AUR package, but the same problem was present on stable modules as well. I'm currently using systemd-networkd systemd-resolved and wpa_supplicant. Before that, I was using NetworkManager. The behavior is essentially the same. 

Pinging a remote server usually results in high packet loss:
```
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=8 ttl=50 time=44.5 ms
64 bytes from 8.8.8.8: icmp_seq=7 ttl=50 time=1057 ms
64 bytes from 8.8.8.8: icmp_seq=11 ttl=50 time=320 ms
64 bytes from 8.8.8.8: icmp_seq=13 ttl=50 time=1054 ms
64 bytes from 8.8.8.8: icmp_seq=14 ttl=50 time=1103 ms
64 bytes from 8.8.8.8: icmp_seq=15 ttl=50 time=130 ms
64 bytes from 8.8.8.8: icmp_seq=16 ttl=50 time=1278 ms
64 bytes from 8.8.8.8: icmp_seq=18 ttl=50 time=279 ms
64 bytes from 8.8.8.8: icmp_seq=19 ttl=50 time=130 ms
64 bytes from 8.8.8.8: icmp_seq=22 ttl=50 time=335 ms
64 bytes from 8.8.8.8: icmp_seq=23 ttl=50 time=131 ms
64 bytes from 8.8.8.8: icmp_seq=24 ttl=50 time=278 ms
```
Pinging a local PC sometimes works fine and sometimes results in stuff like
```
PING 192.168.178.2 (192.168.178.2) 56(84) bytes of data.
64 bytes from 192.168.178.2: icmp_seq=1 ttl=64 time=102 ms
64 bytes from 192.168.178.2: icmp_seq=1 ttl=64 time=103 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=2 ttl=64 time=386 ms
64 bytes from 192.168.178.2: icmp_seq=2 ttl=64 time=386 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=3 ttl=64 time=3423 ms
64 bytes from 192.168.178.2: icmp_seq=3 ttl=64 time=3423 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=4 ttl=64 time=2407 ms
64 bytes from 192.168.178.2: icmp_seq=4 ttl=64 time=2407 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=5 ttl=64 time=1399 ms
64 bytes from 192.168.178.2: icmp_seq=5 ttl=64 time=1399 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=6 ttl=64 time=386 ms
64 bytes from 192.168.178.2: icmp_seq=6 ttl=64 time=386 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=7 ttl=64 time=103 ms
64 bytes from 192.168.178.2: icmp_seq=7 ttl=64 time=104 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=8 ttl=64 time=277 ms
64 bytes from 192.168.178.2: icmp_seq=8 ttl=64 time=585 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=9 ttl=64 time=106 ms
64 bytes from 192.168.178.2: icmp_seq=9 ttl=64 time=107 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=10 ttl=64 time=231 ms
64 bytes from 192.168.178.2: icmp_seq=10 ttl=64 time=424 ms (DUP!)
64 bytes from 192.168.178.2: icmp_seq=11 ttl=64 time=103 ms
64 bytes from 192.168.178.2: icmp_seq=11 ttl=64 time=103 ms (DUP!)
```
At other times there are no duplicate packets, but ping suddenly fluctuates between 2ms and 1000ms. A third failure pattern is that sometimes I suddenly start getting "Destination host unreachable" for about 10 seconds, then the connection comes back. Or sometimes does not, and I have to toggle wifi (rfkill) to make it work again. Once, dmsg showed an oops message as I mentioned in #201 , so maybe that is somehow related, as this happened right when I was starting to get timeouts again.

I have tried toggling power saving as well as software encoding, to no avail.

Is there any information I can provide to make this work?
On an otherwise good laptop, this is driving me insane. It works fine on Windows 10, btw.

**Comment by Soukyuu** [comment] 2017-01-24 17:47
So following a hint on the arch linux forums I tried the current lts kernel instead. The card works flawlessly. Seems like the newer versions introduced a regression.

**Comment by lwfinger** [comment] 2017-01-25 02:57
Too bad no one ever does a bisection to see what, if any, regression there is. I do not see it.

**Comment by Soukyuu** [comment] 2017-01-25 13:00
Jumping between `linux` packages in the arch linux archive, it seems that the first version that causes high packet loss is 4.4.5. Does that help? I've only gotten this laptop recently, so I am late to the game, so to speak.

P.S.: I assume reporting it on the kernel bugzilla would just notify you, as well, and is thus redundant?

**Comment by cnzhx** [comment] 2017-01-28 11:56
I am new to this kind of thing. So please pardon me if I make a mistake here.

I think I have similar issue with this one.  Network controller is `Network controller: Realtek Semiconductor Co., Ltd. RTL8188CE 802.11b/g/n WiFi Adapter (rev 01)`, with driver `rtl8192ce`.

The wireless network works very well before kernel version 4.9.0. However, after v4.9.0, the connection of this wireless card started to behaviour odd. From what I understand, the symptoms are,

1. After updating to kernel 4.9.0, wifi connection works well in a very short time (about several minutes) after boot, then the system cannot connect to any website although the wireless connection seems fine from the indicator of NetworkManager in the systray area. However, the wireless signal indicator changes to full if not before the problem starts. And pinging any IP including local IPs will result in "Destination unreachable" error.
2. To turn off wireless connection then turn it on from NetworkManager yields connection failure, throwing out message of `IP configuration is unavailable `.
3. The wireless connection will connect and work for a very short while if I issue the following commands, `sudo modprobe -r rtl8192ce && sudo modprobe rtl8192ce`. I guess this is equivalent to a reboot for wireless card.
4. Manually set rtl8192ce option `fwlps` to 0 (disabled) will bring the wireless connection to normal but the system will experience high latency and/or package loss when signal from AP is not so strong (e.g. less than 65%).
5. Wireless connection works very well when installing and booting with kernel 4.8.14 with default options of the driver (meaning no need to set `fwlps=0`).
6. Workaround mentioned in 4. works with kernel 4.9.3 and 4.9.4, but with kernel 4.9.0 and 4.9.5, this wireless connection works well when AP signal is strong but experiences high latency and/or package loss when AP signal is poor resulting a very bad connection speed from full bandwidth of the xDSL to only tens of KB/s.
7. I installed wifi driver from the master branch here just now with kernel 4.9.5, the problem of high latency and/or package loss disappeared again (with `fwlps=0` of course).

Hopefully these symptoms are helpful to find the culprit of this issue. Similar reports appear in [1] and [2]:
[1] https://bugzilla.opensuse.org/show_bug.cgi?id=1017471
[2] https://bugzilla.redhat.com/show_bug.cgi?format=multiple&id=1415339

**Comment by lwfinger** [comment] 2017-01-28 19:32
There was a problem with power save, but it was fixed in kernel 4.9.4. The workaround for that problem was to use the option "ips=0". To my knowledge, despite what has been posted, no other combination of any of the "ps" options has ever worked, or even made sense. As the basic power-save mechanism was broken, it made little sense whether software or firmware controlled it. The only fix was to disable it completely, which is what ips=0 does.

I do not run TumbleWeed, thus I have not used the official 4.9.5 kernels, but as I said in the bugzilla entry, I have run the mainline kernels up to my current version of 4.10-rc5. Using that kernel, and the master branch of this repo, I just ran 2000 pings with 0 losses. The maximum return time was 175 msec. My base system is a fully-patched Leap 42.2 KDE. A scan with iw shows my signal strength at -58 dBm.

**Comment by cnzhx** [comment] 2017-01-28 23:44
IIRC, the default options are `ips=1 fwlps=1 swlps=0`. Does it mean that if `fwlps` is set to 0, then all `lps`s are disabled resulting an effectively inactive `ips`? For my case, if I set only `fwlps=0`, the wireless can work fine when signal strength is not so weak. (But I have no specific values.)

Although I am using TW, but I am not an power user and have not tinkled with the system.

After reading your comment, I did the following tries. With all custom options in a file `/etc/modprobe.d/rtl8192ce.conf` created by myself (I do not know where are the default values set).

1. Driver from master branch with kernel 4.9.5.
`sudo modinfo rtl8192ce | grep srcversion
srcversion:     AF7B0DC7BE4DAC4E0F1759F`
1.1 All options are default.
- `ping 192.168.1.1` returns little latency and no package loss
- After around 1 minute, `ping 192.168.1.1` returns `Destination Host Unreachable`.
1.2 Option `ips=0` (keeping default `fwlps=1`).
- `sudo vim /etc/modprobe.d/rtl8192ce.conf` and set only `ips=0`;
- Reboot for sure
Then I have no connection after login. `ping 192.168.1.1` returns `Destination Host Unreachable`.
1.3 Options `fwlps=0` (keeping default `ips=1`)
- `sudo vim /etc/modprobe.d/rtl8192ce.conf` and set only `fwlps=0` (`ips=0` is commented out);
- `sudo modprobe -r rtl8192ce`
- `sudo modprobe rtl8192ce`
Then the wireless connection resumed automatically. 1000 pings to the router (192.168.1.1) shows,
`
--- 192.168.1.1 ping statistics ---
1000 packets transmitted, 1000 received, 0% packet loss, time 1000689ms
rtt min/avg/max/mdev = 0.789/6.498/344.700/20.965 ms
`
This looks quite well to me.

2. Driver from kernel 4.9.5 and with kernel 4.9.5.
I replaced the driver folder in `/lib/modules/$(uname -r)/kernel/drivers/net/wireless/realtek` with backup and reload the module `rtl8192ce`.
`srcversion:     2342051B3DB62D6CF069F77`

2.1 Options `fwlps=0` (keeping default `ips=1`)
- `sudo vim /etc/modprobe.d/rtl8192ce.conf` and set only `fwlps=0` (`ips=0` is commented out);
- `sudo modprobe -r rtl8192ce`
- `sudo modprobe rtl8192ce`
Then the wireless connection resumed automatically. 1000 pings to the router (192.168.1.1) shows 
`
--- 192.168.1.1 ping statistics ---
1000 packets transmitted, 937 received, 6% packet loss, time 1001478ms
rtt min/avg/max/mdev = 0.864/85.821/2521.686/244.881 ms, pipe 3
`
This time, it looks better than the time I just updated the snapshot of TW with kernel 4.9.5. And another run gets,
`
--- 192.168.1.1 ping statistics ---
1000 packets transmitted, 654 received, 34% packet loss, time 1007695ms
rtt min/avg/max/mdev = 0.830/496.388/3701.599/647.471 ms, pipe 4
`

2.2 Option `ips=0` (keeping default `fwlps=1`).
- `sudo vim /etc/modprobe.d/rtl8192ce.conf` and set only `ips=0`;
- `sudo modprobe -r rtl8192ce`
- `sudo modprobe rtl8192ce`
1000 pings to the router (192.168.1.1) shows,
`
--- 192.168.1.1 ping statistics ---
1000 packets transmitted, 663 received, 33% packet loss, time 1007384ms
rtt min/avg/max/mdev = 0.886/475.683/3781.237/637.294 ms, pipe 4
`
2.3 All options are default.
- `ping 192.168.1.1` returns,
`
--- 192.168.1.1 ping statistics ---
1000 packets transmitted, 653 received, 34% packet loss, time 1008099ms
rtt min/avg/max/mdev = 0.865/439.983/10596.736/763.726 ms, pipe 11
`

**Comment by lwfinger** [comment] 2017-01-29 02:32
Use sudo iw wlp3s0 scan | egrep "signal|SSID". That way the SSID will be listed on the line following the signal. Your AP is likely either -50 or -54 dBm.

The default options are built into the driver. I do not know whether the  driver uses firmware or software power save if ips=1 and fwlps=0; however, I do know that power save is enabled, AND that means that kernels between 4.9.0 and 4.9.3 will NOT work correctly, unless ips=0.

I have no idea why your system fails. I have been running the master branch of this repo for nearly 9 hours without a single loss of connection. The work load during this time has been normal web browsing. E-mail downloads, and zypper updates of my main Leap 42.2 system as well as two TW virtual machines. During the update, the downloads reached as high as 4 MB/s.

Have you done a recent pull of this repo? If so, I cannot duplicate your results, which means I have no possibility of debugging your failure. I have the openSUSE kernel git repo on my system, and I am currently building a 4.9.0 kernel from that source. I will test it with ips=0 to see if it works here. As soon as I have run that test, I will report my results.

**Comment by cnzhx** [comment] 2017-01-29 10:33
Yes, you're right. My signal strength is around -53dBm. Based on my experience, I think the signal strength matters a lot in this issue. I encounter the problem only when signal is not so strong with the same configuration. It seems the marginal value is about -53dBm.

I changed the option to `ips=0` yielding
`
Parameters:
    debug               = "0"
    fwlps               = "Y"
    ips                 = "N"
    swenc               = "N"
    swlps               = "N"
`
And tried to ping the router just now with the master branch driver of this repo and the same relative distance to the router getting **a good result**,
`
1000 packets transmitted, 1000 received, 0% packet loss, time 1000512ms
rtt min/avg/max/mdev = 0.967/12.317/458.860/24.638 ms
`
This is not opposite to the result of yesterday with only `ips=0`. So I guess whether 'ips=0` or `fwlps=0` does the trick. The only strange thing to me is that all things go well before kernel 4.9.0 and not stable/constant after that.

As you said the problem was fixed in kernel 4.9.3. Do you mean that no need to set 'ips=0` or `fwlps=0`? And for me, from kernel 4.9.3 to 4.9.4 and 4.9.5, the experiences are not the same. Especially, with kernel 4.9.5, I have to change to the master branch of this repo to make my wireless work fine.

The master branch of this repo works for me as well. But I need to set extra option as `fwlps=0`. Otherwise, it does not work well. I only learnt to use this repo yesterday, and I downloaded it using link "https://codeload.github.com/lwfinger/rtlwifi_new/tar.gz/master" about 22 hours ago.

I do not know much about this stuff. So if you need any information, please ask for it directly.

**Comment by Soukyuu** [comment] 2017-01-29 12:42
Well, it's not signal strength in my case. `sudo iw wlp3s0 scan | egrep "signal|SSID"` gives
 `signal: -21.00 dBm`

Device ID is:
```
03:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8188CE 802.11b/g/n WiFi Adapter [10ec:8176] (rev 01)
```

On current lts, systool gives the following default configuration:
```
Module = "rtl8192ce"

Parameters:
    debug               = "0"
    fwlps               = "Y"
    ips                 = "Y"
    swenc               = "N"
    swlps               = "N"
```
This is the same configuration as is displayed with the freshly updated 4.9.6. The connection is as unstable as it was on 4.8.13, though. I will try messing with ips/fwlps options, but I don't think that's it.

**Comment by Soukyuu** [comment] 2017-01-29 13:04
Running  4.9.6 with 
```
Module = "rtl8192ce"

Parameters:
    debug               = "0"
    fwlps               = "Y"
    ips                 = "N"
    swenc               = "N"
    swlps               = "N"
```
results in 8 working pings, followed by 100% packet loss.

Running 4.9.6 with
```
Module = "rtl8192ce"

Parameters:
    debug               = "0"
    fwlps               = "N"
    ips                 = "Y"
    swenc               = "N"
    swlps               = "N" 
```
works fine so far. Low ping, no packet loss. I tried moving between floors (I have a repeater on each of them) and there were some packet lost when moving from one station to another, but the connection did not die. 

So maybe it's the `fwlps` option that's causing issues now. On 4.8.13, even setting `fwlps`/`ips` to 0 didn't help, though.

**Comment by lwfinger** [comment] 2017-01-29 17:36
First of all, the default options have not changed in a long time, thus systool or modinfo will give the same result no matter what version you are running. It was the underlying code that changed. As I said before, there was a BUG in that code that caused failures in the power-save function for kernels before version 4.9.4. The problem showed up as lond as ips was not zero. Period!  The bug was introduced in 4.9.0, but some distros backport changes and you may see it earlier. In any case, you need to set "ips=0". No other fix will do. This repo does contain that fix and a bunch of other changes - it is essentially the code from kernel 4.10-rc5.

My experience is that signal strengths of -58 dBm or higher work OK.

**Comment by lwfinger** [comment] 2017-01-30 02:17
I just got mail from a Debian user who reported and fixed a problem that caused the wrong firmware to be loaded for some models of the RTL81{88,92}CE. As it happens, my test chip is not affected, thus I did not see the problem. That likely explains why I could not reproduce the problem.

A fix has been prepared and was pushed a few minutes ago into the master branch. I will also push the fix to mainline, but that may take some time to propagate through the system.

**Comment by cnzhx** [comment] 2017-01-30 08:52
Yes, this new master branch works for me now. Tested with the default parameters on kernel 4.9.5 in openSUSE Tumbleweed in my work place.

P.S. Could you please tell me how to check which firmware is loaded?

**Comment by lwfinger** [comment] 2017-01-30 15:31
It is logged in the dmesg output.

**Closed by lwfinger** 2017-01-30 15:31 UTC

**Comment by Soukyuu** [comment] 2017-02-04 15:21
This seems to be what was causing the issue. After building the aur package with the current rtlwifi_new master, the card works fine with default module options - many thanks for fixing this.
