### ISSUE TITLE
Wifi hard block on rtl8723be (HP Pavilion 15)

### ISSUE THREAD

**Issue by absdata** [lwfinger/rtlwifi_new#124] opened 2016-05-30 02:05 UTC
Hello!
I spend many time, but can't solve problem with Wi-Fi. When laptop enter in sleep mode, after wakeup wifi does not work. It always need reboot the system.
I use rock.new_btcoex branch of driver. Master branch not work for me.

cat /etc/modprobe.d/rtl8723be.conf
`options rtl8723be ant_sel=2 fwlps=0 swlps=0 ips=0`

uname -r
`3.16.0-4-amd64`

uname -v
`#1 SMP Debian 3.16.7-ckt25-2 (2016-04-08)`

lspci | grep RTL
`08:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
09:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8101E/RTL8102E PCI Express Fast Ethernet controller (rev 0a)`

BT also not working, but I solve this broblem with long audio cable. 

Laptop:
HP Pavilion 15-ab225ur, P3L10EA

Please help.

**Comment by snaunton** [comment] 2016-05-30 02:28
Workaround maybe? (works with Ubuntu):

Create /etc/pm/sleep.d/00_wireless_sleep:

```
#!/bin/sh
case "$1" in
  suspend|hibernate)
 	/sbin/rmmod rtl8723be
  ;;
  resume|thaw)
	sleep 5 
	/sbin/rmmod rtl8723be
	sleep 2 
	/sbin/modprobe rtl8723be
  ;;
esac

exit 0
```

Then:

chmod +x /etc/pm/sleep.d/00_wireless_sleep

**Comment by absdata** [comment] 2016-05-30 04:06
> Workaround maybe? (works with Ubuntu):
Thank you!

I tied. But it does not work for me.

Also I tried upgrade my kernel to 4.5.3.

And tried blacklist hp-wmi in /etc/modprobe.d/blacklist.conf

**Comment by absdata** [comment] 2016-05-30 04:43
Here is my log after sleep mode:
```
May 30 12:34:23 Lauder kernel: [ 1158.490328] Using firmware rtlwifi/rtl8723befw.bin
May 30 12:34:23 Lauder kernel: [ 1158.490489] rtlwifi:_rtl_init_hw_ht_capab():<0-0> 1T1R
May 30 12:34:23 Lauder kernel: [ 1158.490491] rtlwifi:rtl_regd_init():<0-0> rtl: EEPROM regdomain: 0x20 conuntry code: 11
May 30 12:34:23 Lauder kernel: [ 1158.490514] rtl8723be 0000:08:00.0: firmware: direct-loading firmware rtlwifi/rtl8723befw.bin
May 30 12:34:23 Lauder kernel: [ 1158.491325] ieee80211 phy2: Selected rate control algorithm 'rtl_rc'
May 30 12:34:23 Lauder kernel: [ 1158.492039] rtl8723be:rtl8723be_gpio_radio_on_off_checking():<0-0> GPIOChangeRF  - HW Radio OFF, RF OFF
May 30 12:34:23 Lauder kernel: [ 1158.492041] rtlwifi: wireless switch is on
May 30 12:34:23 Lauder kernel: [ 1158.492122] rtl_pci:rtl_pci_intr_mode_legacy():<0-0> Pin-based Interrupt Mode!
May 30 12:34:23 Lauder NetworkManager[599]: <info> rfkill3: found WiFi radio killswitch (at /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/ieee80211/phy2/rfkill3) (driver rtl8723be)
May 30 12:34:23 Lauder NetworkManager[599]: <info> WiFi now disabled by radio killswitch
May 30 12:34:23 Lauder NetworkManager[599]: <info> (wlan0): using nl80211 for WiFi device control
May 30 12:34:23 Lauder NetworkManager[599]: <info> (wlan0): driver supports Access Point (AP) mode
May 30 12:34:23 Lauder NetworkManager[599]: <info> (wlan0): new 802.11 WiFi device (driver: 'rtl8723be' ifindex: 5)
May 30 12:34:23 Lauder NetworkManager[599]: <info> (wlan0): exported as /org/freedesktop/NetworkManager/Devices/4
May 30 12:34:23 Lauder NetworkManager[599]: <info> (wlan0): device state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
May 30 12:34:23 Lauder NetworkManager[599]: <info> (wlan0): preparing device
May 30 12:34:23 Lauder NetworkManager[599]: <info> devices added (path: /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/net/wlan0, iface: wlan0)
May 30 12:34:23 Lauder NetworkManager[599]: <info> device added (path: /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/net/wlan0, iface: wlan0): no ifupdown configuration found.
May 30 12:34:24 Lauder ModemManager[603]: <warn>  Couldn't find support for device at '/sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0': not supported by any plugin
May 30 12:34:46 Lauder ovpn-client[637]: TLS Error: TLS key negotiation failed to occur within 60 seconds (check your network connectivity)
May 30 12:34:46 Lauder ovpn-client[637]: TLS Error: TLS handshake failed
```

**Comment by lwfinger** [comment] 2016-05-30 15:32
Something in you ruser space is killing the radio. See the "WiFi now disabled by radio killswitch" message. The driver is ready to go, but it cannot overide that setting.

You need to look at "rfkill list" to see where the blockage is coming from.  Note: User space code is a function of your distro. You will probably need to ask there on how to fix the problem.

**Comment by absdata** [comment] 2016-05-31 07:23
@lwfinger Thank you for your answer!
It looks like driver killing the radio.

Then I remove driver, it removes kill.
`rmmod rtl8723be`

```
May 31 15:08:44 Lauder avahi-daemon[626]: Withdrawing workstation service for wlan0.
May 31 15:08:44 Lauder NetworkManager[2608]: <info> (wlan0): device state change: unavailable -> unmanaged (reason 'removed') [20 10 36]
May 31 15:08:44 Lauder NetworkManager[2608]: <info> devices removed (path: /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/net/wlan0, iface: wlan0)
May 31 15:08:44 Lauder ModemManager[603]: <info>  (net/wlan0): released by modem /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0
May 31 15:08:44 Lauder NetworkManager[2608]: <info> radio killswitch /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/ieee80211/phy3/rfkill4 disappeared
May 31 15:08:44 Lauder NetworkManager[2608]: <info> WiFi now enabled by radio killswitch

```

Then I add it again.
`modprobe rtl8723be`

```
May 31 15:09:35 Lauder kernel: [ 1092.756710] Using firmware rtlwifi/rtl8723befw.bin
May 31 15:09:35 Lauder kernel: [ 1092.756943] rtl8723be 0000:08:00.0: firmware: direct-loading firmware rtlwifi/rtl8723befw.bin
May 31 15:09:35 Lauder kernel: [ 1092.757872] ieee80211 phy5: Selected rate control algorithm 'rtl_rc'
May 31 15:09:35 Lauder kernel: [ 1092.758406] rtlwifi: wireless switch is on
May 31 15:09:35 Lauder NetworkManager[2608]: <info> rfkill6: found WiFi radio killswitch (at /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/ieee80211/phy5/rfkill6) (driver rtl8723be)
May 31 15:09:35 Lauder NetworkManager[2608]: <info> WiFi now disabled by radio killswitch
May 31 15:09:35 Lauder NetworkManager[2608]: <info> (wlan0): using nl80211 for WiFi device control
May 31 15:09:35 Lauder NetworkManager[2608]: <info> (wlan0): driver supports Access Point (AP) mode
May 31 15:09:35 Lauder NetworkManager[2608]: <info> (wlan0): new 802.11 WiFi device (driver: 'rtl8723be' ifindex: 8)
May 31 15:09:35 Lauder NetworkManager[2608]: <info> (wlan0): exported as /org/freedesktop/NetworkManager/Devices/7
May 31 15:09:35 Lauder NetworkManager[2608]: <info> (wlan0): device state change: unmanaged -> unavailable (reason 'managed') [10 20 2]
May 31 15:09:35 Lauder NetworkManager[2608]: <info> (wlan0): preparing device
May 31 15:09:35 Lauder NetworkManager[2608]: <info> devices added (path: /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/net/wlan0, iface: wlan0)
May 31 15:09:35 Lauder NetworkManager[2608]: <info> device added (path: /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/net/wlan0, iface: wlan0): no ifupdown configuration found.
```

Let's see details of kill.
`udevadm info -a -p /sys/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/ieee80211/phy5/rfkill6`

```
Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

  looking at device '/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/ieee80211/phy5/rfkill6':
    KERNEL=="rfkill6"
    SUBSYSTEM=="rfkill"
    DRIVER==""
    ATTR{hard}=="1"
    ATTR{name}=="phy5"
    ATTR{soft}=="0"
    ATTR{type}=="wlan"
    ATTR{claim}=="0"
    ATTR{index}=="6"
    ATTR{state}=="2"
    ATTR{persistent}=="0"

  looking at parent device '/devices/pci0000:00/0000:00:1c.2/0000:08:00.0/ieee80211/phy5':
    KERNELS=="phy5"
    SUBSYSTEMS=="ieee80211"
    DRIVERS==""
    ATTRS{name}=="phy5"
    ATTRS{index}=="5"
    ATTRS{addresses}=="a8:a7:95:30:99:0d"
    ATTRS{macaddress}=="a8:a7:95:30:99:0d"
    ATTRS{address_mask}=="00:00:00:00:00:00"

  looking at parent device '/devices/pci0000:00/0000:00:1c.2/0000:08:00.0':
    KERNELS=="0000:08:00.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="rtl8723be"
    ATTRS{irq}=="18"
    ATTRS{subsystem_vendor}=="0x103c"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x028000"
    ATTRS{index}=="1"
    ATTRS{label}=="Realtek RTL8723BE 802.11b/g/n 1x1Wi-Fi + BT4.0 Combo Adapter"
    ATTRS{driver_override}=="(null)"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{dma_mask_bits}=="32"
    ATTRS{local_cpus}=="0f"
    ATTRS{device}=="0xb723"
    ATTRS{enable}=="1"
    ATTRS{msi_bus}=="1"
    ATTRS{local_cpulist}=="0-3"
    ATTRS{vendor}=="0x10ec"
    ATTRS{subsystem_device}=="0x804c"
    ATTRS{numa_node}=="-1"
    ATTRS{d3cold_allowed}=="1"

  looking at parent device '/devices/pci0000:00/0000:00:1c.2':
    KERNELS=="0000:00:1c.2"
    SUBSYSTEMS=="pci"
    DRIVERS=="pcieport"
    ATTRS{irq}=="44"
    ATTRS{subsystem_vendor}=="0x103c"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x060400"
    ATTRS{driver_override}=="(null)"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{dma_mask_bits}=="32"
    ATTRS{local_cpus}=="0f"
    ATTRS{device}=="0x9c94"
    ATTRS{enable}=="1"
    ATTRS{msi_bus}=="1"
    ATTRS{local_cpulist}=="0-3"
    ATTRS{vendor}=="0x8086"
    ATTRS{subsystem_device}=="0x8096"
    ATTRS{numa_node}=="-1"
    ATTRS{d3cold_allowed}=="0"

  looking at parent device '/devices/pci0000:00':
    KERNELS=="pci0000:00"
    SUBSYSTEMS==""
    DRIVERS==""
```

**Comment by lwfinger** [comment] 2016-05-31 16:34
The driver cannot kill the radio. The kill is coming from somewhere in your user space code. You need to check with Debian forums to find out why.

**Comment by lwfinger** [comment] 2016-05-31 16:44
A little more information: The F12 key should be toggling the HARD lock, not the SOFT one. That function should be handled by the wmi routines, but you have blacklisted them, thus I have no idea what code is interpreting that button.

Does unloading and reloading rfkill help?

**Comment by absdata** [comment] 2016-05-31 19:33
Unloading rfkill not help. Also I tried rm /dev/rfkill and it not help.
I checked forums. Actualy spend 2 days for reading. May be it can be ACMI, but without ACMI WIFI not work. I tried to enable wakeup for this card in ACMI and this does not help.
Also tried remove device from /etc/udev/rules.d and /lib/udev/rules.d/.
You gave me a great idea about user space code, but I can't find any source of kill. 
With wmi it not work too. No idea...

**Comment by nicoserafino** [comment] 2016-06-07 11:14
Hi absdata,
I had the same issue on my HP 15 r230nl with rtl8723be.
I fixed this way
Open a terminal and type the following:

`sudo nano /etc/systemd/system/wifi-resume.service` Now paste the script in there with a right click. Exit with CTRL + X and press Y to save. Now to activate it: `sudo systemctl enable wifi-resume.service`

Script:

```
#/etc/systemd/system/wifi-resume.service
#sudo systemctl enable wifi-resume.service
[Unit]
Description=Restart networkmanager at resume
After=suspend.target
After=hibernate.target
After=hybrid-sleep.target

[Service]
Type=oneshot
ExecStart=/bin/systemctl restart network-manager.service

[Install]
WantedBy=suspend.target
WantedBy=hibernate.target
WantedBy=hybrid-sleep.target
```

Source: http://askubuntu.com/questions/761180/wifi-doesnt-work-after-suspend-after-16-04-upgrade


This way I solved your issue, but my bluetooth still doesn't work. Is your bluetooth working?

**Comment by absdata** [comment] 2016-06-08 06:49
@nicoserafino Thank you!

Restarting network-manager not help in my case. Because I cant remove hard block.

**Comment by manu-chroma** [comment] 2016-06-17 12:23
Hey, I'm having same problem since I installed these drivers. Apart from this issue they're working perfectly fine for me.

@absdata Did you find any fix ? 
I'm using Ubuntu Gnome 16.04
Would be happy to share any logs if required.

**Comment by absdata** [comment] 2016-06-19 02:36
@manu-chroma Unfortunately I have not found the solution. Each time I just reboot the computer (

**Comment by DiamondBond** [comment] 2016-08-02 17:04
Just dropping in to say i also have this issue, ive also tried pretty much anything and everything i can find on the web and nothing fixes it, there was a [patch submitted to hp-wmi.c](https://github.com/torvalds/linux/commit/fc8a601e1175ae351f662506030f9939cb7fdbfe) which was supposed to fix this issue, but after installing mainline 4.7 on ubuntu 16.04.1 LTS, no results have been yielded, after a simple suspend, the wifi device is hardblocked - in this case, a rtl8723be, guess ill be switching back to windows for the time being.

**Comment by manu-chroma** [comment] 2016-08-02 17:10
Hey @DiamondBond,
I really appreciate your effort. Suffering from same problem. 

I have a question. If you submitted the patch, it must be working during the time of submission, or not ?

@lwfinger You suggested doing this long ago. Any suggestions now ?

**Comment by manu-chroma** [comment] 2016-08-02 17:15
Additional : https://bugzilla.kernel.org/show_bug.cgi?id=69131

**Comment by DiamondBond** [comment] 2016-08-02 17:19
@manu-chroma I did not submit the patch, alex hung did, up until Jun 13 it was an [unofficial patch](https://bugzilla.kernel.org/attachment.cgi?id=122901) that you could apply yourself to hp-wmi.c and then compile & install this patched kernel, but now it has been officially merged into the linux kernel it should solve this issue without needing that patch since its already merged but it does not seem to have any resolve unfortunately.

ive read through that bugzilla report so many times, it all talks about this patch which is now in mainline, so there shouldnt be an issue for us, but there still is ;-;

**Comment by manu-chroma** [comment] 2016-08-02 17:25
My bad!
Is there anything possible, at this point of time, which can be done ?

Is there a possibility that this patch works with the default linux drivers and fail when you use ```rtlwifi_new``` drivers ?

**Comment by DiamondBond** [comment] 2016-08-02 17:28
@manu-chroma 
Not that i am aware of, ive used both rtlwifi_new and the default ones, there is no difference that i can see relating to this issue.
I did find this [little snippet of info on the opensuse forums](https://forums.opensuse.org/showthread.php/506003-Lenovo-G40-RTL8723be-wireless-disabled-by-hardware-(wifi-and-bluetooth)) , but after individually blacklisting hp-wmi, hp-wireless and any other hp related modules and then rebooting, suspending, and then enabling then disabling the next to try them all, none have yielded results so far.

**Comment by manu-chroma** [comment] 2016-08-02 17:32
Thanks. I'll get back to here if that works for me. 

Thanks again for the info.

**Comment by DiamondBond** [comment] 2016-08-02 17:33
No problem, please do come back with any info you have @manu-chroma , i hope we can resolve this issue since its plaguing my laptop from linux use which i do not like at all.

**Comment by manu-chroma** [comment] 2016-08-02 17:36
Sure thing, I'll get back soon. I really want to get this fixed too.

**Comment by DiamondBond** [comment] 2016-08-02 17:55
@manu-chroma i just realized i have the exact same laptop as you (to some extent, i have the i7u, 1tb hdd, 8gb ram & 940m model, but it also has rtl8723be wifi obviously.)

**Comment by lwfinger** [comment] 2016-08-02 21:50
I have read all these postings, and what you fail to recognize is that blocking the wifi is largely controlled by user-space code. Do all of you run the same distro? If so, that is the place to start. With openSUSE Leap 42.1, I do not have the difficulty, thus there is nothing I can do to debug it.

**Comment by absdata** [comment] 2016-08-03 03:22
I continue to look for a solution. 
uname -v
`#1 SMP Debian 4.5.3-2~bpo8+1 (2016-05-13)`

Laptop:
`HP Pavilion 15-ab225ur, P3L10EA`

**Comment by DiamondBond** [comment] 2016-08-03 07:22
@lwfinger oh right, then trying another distro might help, well ill try out arch this evening and if that does not yield any promising results, ill try openSUSE.

**Comment by manu-chroma** [comment] 2016-08-03 11:40
@DiamondBond I can try Fedora 24 this weekend.

**Comment by DiamondBond** [comment] 2016-08-03 13:26
@lwfinger arch seems to have yielded no magical results, i will try openSUSE tonight.
@manu-chroma sweet!, as i said above, im going to try openSUSE later, archlinux didnt work well at all with xfce, after suspending and waking up, wifi is hard blocked, same as on ubuntu.

**Comment by DiamondBond** [comment] 2016-08-03 16:47
@lwfinger sorry to disturb, but may i know what de/wm & network manager you use in openSUSE?

**Comment by lwfinger** [comment] 2016-08-03 20:29
KDE and NetworkManager

**Comment by DiamondBond** [comment] 2016-08-04 11:00
@lwfinger @absdata Ive been fiddling with openSUSE basically all morning and ive come across a workaround, on distro's like ubuntu and etc, hibernation always broke and never worked, only suspend did, when using openSUSE, i noticed hibernation worked flawlessly and upon awakening the device from hibernation, the network was working fine. (because it is not fiddling with suspend at all and its mechanism and etc) So i never managed to load the rtlwifi_new drivers into opensuse, when running modinfo -p rtl8723be, it never showed "ant_sel" as a parameter so i assume it never actually used the rtlwifi_new drivers, so i ditched the opensuse idea all together because i had remembered using crunchbang plus plus on my x220 which has hibernation working out of the box like opensuse does, and now with rtlwifi_new drivers loaded and working in this debian based distro (CB++), upon de-hibernation of the device, wifi works 100%.

Mini tutorial @absdata : 
- Download & Install CBPP (you need an ethernet connection during install)
- Boot, and complete the setup (theres a little popup term on first start which will ask you if you want to install some nice meta packages like java, libreoffice and etc, choose what you want)
- sudo apt-get update && sudo apt-get install git vim rfkill && sudo apt-get install linux-headers-$(uname -r)
- mkdir -p ~/bin/rtlwifi/
- git clone git://github.com/lwfinger/rtlwifi_new ~/bin/rtlwifi
- git checkout rock.new_btcoex
- cd ~/bin/rtlwifi/
- make && sudo make install
- sudo modprobe -rv rtl8723be
- sudo modprobe -v rtl8723be ips=0 ant_sel=2
then i also created some files in modprobe.d to keep these settings permanent.
- sudo touch /etc/modprobe.d/50-rtl8723be.conf
- sudo vim /etc/modprobe.d/50-rtl8723be.conf
and paste this: "options rtl8723be ips=0 ant_sel=2"
boom, done.
After doing all the following, i have a 100% working debian install (which i need to theme and configure to my liking now.), the only minor gripe ive come across so far is that the touchpad drivers/configuration (synaptics touchpad here) is shit out of the box, and ill need to find a way to configure them so it works more like ubuntu's default touchpad settings or literally any other linux distro.
Hopefully this can class as a solution and this can be closed :)

**Comment by manu-chroma** [comment] 2016-08-04 13:37
Hey @DiamondBond, 
Thanks for the great tutorial. I really never tried hibernating before. 

It worked for me on Ubuntu 16.04 using ```sudo systemctl hibernate```
And as you said, wifi works 100% :smiley:

**Comment by DiamondBond** [comment] 2016-08-04 14:41
@manu-chroma No problem! I actually decided to install ubuntu since i could not for the life of me configure/get comfortable with debian on a laptop, on a desktop though, it runs great.
Im going to try setting everything up on ubuntu now :)

**Comment by DiamondBond** [comment] 2016-08-05 14:15
so after about 1 day of configuring/use/testing, using hibernation and etc, everything seems to work great so far, unity is also alot better than it was 3 years ago.

**Comment by lwfinger** [comment] 2016-08-05 15:26
It would not have been possible to make it much worse that it was!

**Comment by manu-chroma** [comment] 2016-08-05 16:45
@DiamondBond It's working really well for me too!

I heard that heavy use of hibernation affects hard drive life due to huge amount of data being written and read. Just a little wary of that fact.

**Comment by lwfinger** [comment] 2016-08-05 16:56
When it hibernates, the system writes a compressed version of memory to the swap file. That amount of data will be roughly 1/2 the size of RAM. In addition, the write and the corresponding read on resume will be nearly contiguous and will involve very few seeks. By comparison, a reboot would consume much more data and a lot more seeks, which are harder on your hard drive.

If you are that worried about your hard drive, I suggest that you shut down your computer immediately, place it in a locked closet, and throw away the key. Your machine is clearly too fragile to be used. :)

**Comment by manu-chroma** [comment] 2016-08-05 16:59
@lwfinger I think both part of your answer helped in instilling some confidence in me. :laughing:

**Comment by BasioMeusPuga** [comment] 2016-08-07 04:13
@DiamondBond @manu-chroma @lwfinger 
If you'll read through that bug report, especially https://bugzilla.kernel.org/show_bug.cgi?id=69131#c18, you'll see the exact problem we have here described in some detail. David Ward seems to think this bug is separate from the existing issues with (and fix for) the hp-wmi.c module.

Personally, I've been waiting for kernel 4.7 to hit. That's when both the code from this repo and fix to hp.wmi were supposed to be integrated.

**Comment by DiamondBond** [comment] 2016-08-07 08:38
@basiomeuspuga yes, we have a workaround which is basically: never suspend, just hibernate, its been working great for me so far but fixing suspend will be nice, and I kept track of the hp-wmi.c patch and it was submitted a few months back so it should have been merged in 4.6 if I'm not mistaken? but 4.7 will have the new rtlwifi_new stuffs in it with ant_sel right @lwfinger ? If so then I will be waiting for that, otherwise I'll hop onto arch and see what the situation is like!

**Comment by absdata** [comment] 2016-08-07 11:05
I replaced suspend to hibernate in all my settings. Let's wait for fixes.
Thank you @DiamondBond @manu-chroma @lwfinger

**Comment by lwfinger** [comment] 2016-12-02 20:03
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Closed by lwfinger** 2016-12-02 20:03 UTC

**Comment by DiamondBond** [comment] 2016-12-04 14:47
Glad to hear this! :)

**Comment by manu-chroma** [comment] 2016-12-04 15:54
I can confirm that main branch is very much stable and a definite improvement over the ``rock.new_btcoex`` drivers which I was using previously. 

Thanks so much lwfinger!

**Comment by axelsimon** [comment] 2017-02-21 10:57
@lwfinger Could you specify which version that is, more specifically?

**Comment by lwfinger** [comment] 2017-02-21 15:33
The current one, of course. You are using git to pull the updates rather than getting a zip file, are you not? Once you have an active git repo, then "git log" will let you see the update commits.

The current repo is at commit ad9a9f2ffe620c8.

**Comment by upuneetu** [comment] 2018-01-11 14:03
I'm using the latest driver for rtl8723be on ubuntu 16.04.2, but I still face this problem of wifi hard block on suspend. I've reinstalled the whole OS to make sure that other user services aren't meddling with it, but even with a fresh install, I still face this problem.

**Comment by lwfinger** [comment] 2018-01-11 16:20
I cannot duplicate the problem, thus I doubt that it is a driver issue. Find out what it takes to issue commands on suspend/resume in your distro, and add a "modprobe -r rtl8723be" on suspend, and a "modprobe rtl8723be" on resume. This "fix" has been reported several times.

**Comment by arpanbiswas97** [comment] 2018-11-20 13:42
Still facing the same problem. I am running a fresh Ubuntu 18.04 installation with the latest driver for rtl8723be on HP Pavilion ab220tx. Network manager says no wifi adapter found every time after a suspend. Tried restarting the network manager but it didn't work for me. I need to restart my laptop to get connected to wifi every time.

**Comment by lwfinger** [comment] 2018-11-20 15:37
I do not think the problem is with the driver. I am not sure that I tested with kernel 4.15, which is what I believe to be in 18.04, but I did just test with the driver in 4.20.0-rc2+. When I suspend my openSUSE Tumbleweed system and restart it, the network comes back up immediately. This network is controlled by NetworkManager.

Note that the driver merely does whatever I/O it is told to do. There are a number of user tasks being done that control the sleep and restore process. The first messages in the dmesg output regarding the wifi device are as follows:

wlan0: authenticate with 20:e5:2a:01:f7:ea
wlan0: send auth to 20:e5:2a:01:f7:ea (try 1/3)
wlan0: authenticated
wlan0: associate with 20:e5:2a:01:f7:ea (try 1/3)
wlan0: RX AssocResp from 20:e5:2a:01:f7:ea (capab=0x11 status=0 aid=6)
wlan0: associated

To collect more information, will the sequence below restart the network?

sudo modprobe -rv rtl8723be && sudo modprobe -v rtl8723be

**Comment by arpanbiswas97** [comment] 2018-11-20 16:54
I tried the sequence above and it did not restart the network. Here is the output I got:

rmmod rtl8723be
rmmod rtl_pci
rmmod rtl8723_common
rmmod btcoexist
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211
insmod /lib/modules/4.15.0-39-generic/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.15.0-39-generic/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.15.0-39-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.15.0-39-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.15.0-39-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko 
insmod /lib/modules/4.15.0-39-generic/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.15.0-39-generic/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko ant_sel=2 

I shall try to find if any user task that controls the sleep and restore process is responsible for the wifi hard block.

**Comment by lwfinger** [comment] 2018-11-21 21:43
After suspend, what does "rfkill list" show?

**Comment by k3dves** [comment] 2018-12-02 05:54
I've got the exact same issue as @arpanbiswas97, my driver is rtl8723be
Below is the output for some commands:

> sudo modprobe -rv rtl8723be && sudo modprobe -v rtl8723be
`rmmod rtl8723be
rmmod rtl_pci
rmmod rtl8723_common
rmmod btcoexist
rmmod rtlwifi
rmmod mac80211
rmmod cfg80211
insmod /lib/modules/4.18.0-kali1-amd64/kernel/net/wireless/cfg80211.ko 
insmod /lib/modules/4.18.0-kali1-amd64/kernel/net/mac80211/mac80211.ko 
insmod /lib/modules/4.18.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtlwifi.ko 
insmod /lib/modules/4.18.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl_pci.ko 
insmod /lib/modules/4.18.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723com/rtl8723-common.ko 
insmod /lib/modules/4.18.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/btcoexist/btcoexist.ko 
insmod /lib/modules/4.18.0-kali1-amd64/kernel/drivers/net/wireless/realtek/rtlwifi/rtl8723be/rtl8723be.ko fwlps=N ips=N swlps=N swenc=Y disable_watchdog=1 ant_sel=1`

After suspend the rfkill list shows
>  rfkill list
`3: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: yes`

**Comment by lwfinger** [comment] 2018-12-02 17:17
Either your wmi code in the kernel or your distro's user code is not handling airplane mode correctly. In either case, the driver is not responsible. It is doing exactly what the system is telling it to do.

**Comment by arpanbiswas97** [comment] 2018-12-02 18:06
Agreed. It is not the driver's fault. I recently installed Fedora 29 on my machine where the WiFi works out-of-the-box. So, I didn't have to install rtlwifi_new. But I am still experiencing the same issue. WiFi adapter not found after suspend. I guess the only workaround is to use hibernation instead of suspend.

**Comment by manu-chroma** [comment] 2018-12-03 16:52
Faced the same problem in the past, did hibernate for sometime. Then I ended up going for a usb wifi and blacklisting internal wifi driver. Putting on sleep does not hard block the external wifi driver. Works well.

**Comment by lwfinger** [comment] 2018-12-03 17:41
Yes, most external USB drivers pay no attention to the RFKILL signal. If you were to put your laptop into an environment where radio silence is required, you will need to pull the stick.
