### ISSUE TITLE
High system loads

### ISSUE THREAD

**Issue by ghost** [lwfinger/rtlwifi_new#44] opened 2015-04-30 12:24 UTC
Hi.

Arch user here. Just bought a Lenovo E555 which has RTL8723BE. The detected driver had problems with connecting to the network. It would drop out all the time. I installed the driver from this repo, and the connection was stable. Unfortunately the system crawls to a standstill with high system loads when the network is being accessed. The system is stable on wired connection. Any ideas what is going on. Given the WIFI form factor (M.2) I am loathed to replace the chip. Thanks.

Arch thread discussing issue: https://bbs.archlinux.org/viewtopic.php?id=196770

**Comment by lwfinger** [comment] 2015-05-01 23:51
I need more details on how this "high system load" is being manifested. Your "htop" display shows chromium as taking a lot of time. Do you see the same problem with Firefox? What does htop show when no browser is loaded? Are there excessive interrupts in "cat /proc/interrupts"?

You did not specify what branch of this repo you are using, thus I will assume "master". Does using the "rock" branch help?

**Comment by kafkaesque1978** [comment] 2015-05-02 06:51
Thanks for responding. Yes the same behaviour happens in FF. Generally speaking there is a much lower system load when no network is being accessed, between less that 1 and 6. Network activity sends this up to 10-15. I was using master, but rock isn't any different. Still unusable. It is important to recognise that the system works as expected over a wired connection, doing the same things. There are no massive slowdowns and the system is comparable to the Windows install in terms of speed and responsiveness. 

cat /proc/interrupts:
`````````````````
            CPU0       CPU1       CPU2       CPU3       
   0:         55          0          0          0   IO-APIC-edge      timer
   1:       1960       1758       2881       4044   IO-APIC-edge      i8042
   8:          0          0          1          0   IO-APIC-edge      rtc0
   9:        837        466        916        879   IO-APIC-fasteoi   acpi
  12:      49816      38693      67762     116381   IO-APIC-edge      i8042
  16:        171        178        180        217   IO-APIC   16-fasteoi   snd_hda_intel
  17:         19          1         11         18   IO-APIC   17-fasteoi   ehci_hcd:usb3, ehci_hcd:usb4
  18:      44596      41558      69768     103471   IO-APIC   18-fasteoi   ohci_hcd:usb5, ohci_hcd:usb6, ohci_hcd:usb7
  24:          0          0          0          0   PCI-MSI-edge      PCIe PME
  25:          0          0          0          0   PCI-MSI-edge      PCIe PME
  26:          0          0          0          0   PCI-MSI-edge      PCIe PME
  28:          7          4          7          7   PCI-MSI-edge      rtsx_pci
  29:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  30:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  31:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  32:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  33:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  34:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  35:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  36:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  37:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  38:          0          0          0          0   PCI-MSI-edge      xhci_hcd
  39:      49849      36871      69797      87290   PCI-MSI-edge      0000:00:11.0
  42:     826750     873066    1623646    1411451   PCI-MSI-edge      enp1s0
  44:         36         39         40         37   PCI-MSI-edge      snd_hda_intel
  45:      93426      59640     115783     147494   IO-APIC   16-fasteoi   rtl_pci
  46:     393944     403626     588368     841361   PCI-MSI-edge      fglrx[0]@PCI:0:1:0
 NMI:        398        403        416        403   Non-maskable interrupts
 LOC:    3360199    3485406    3341867    3403671   Local timer interrupts
 SPU:          0          0          0          0   Spurious interrupts
 PMI:        398        403        416        403   Performance monitoring interrupts
 IWI:          0          0          2          0   IRQ work interrupts
 RTR:          0          0          0          0   APIC ICR read retries
 RES:    3017414    2939169    2928703    2787777   Rescheduling interrupts
 CAL:      11618      10304      12541      11571   Function call interrupts
 TLB:     195731     177347     204840     178204   TLB shootdowns
 TRM:          0          0          0          0   Thermal event interrupts
 THR:          0          0          0          0   Threshold APIC interrupts
 MCE:          0          0          0          0   Machine check exceptions
 MCP:         41         40         40         40   Machine check polls
 HYP:          0          0          0          0   Hypervisor callback interrupts
 ERR:          0
 MIS:          0
``````````````````````

**Comment by kafkaesque1978** [comment] 2015-05-20 11:25
No update on this?

**Comment by lwfinger** [comment] 2015-05-20 15:53
Sorry, but I cannot reproduce this. There was a recent commit entitled "rtlwifi_new: Remove unexpected interrupt cleaning to avoid tx blocking" that might cause the effect. Have you pulled the repo since May 15?

It is very difficult to fix something that I cannot reproduce, and my budget certainly does not include purchasing a $500 tablet to find out why it is having this problem.

**Comment by kafkaesque1978** [comment] 2015-05-23 11:35
Just an update. I managed to get hold of the same card from a different E555. Same behaviour occurs. So we can assume the card isn't faulty. Updating the driver hasn't improved the situation. Did purchase an alternative card (Intel) however that doesn't work either (but for different reasons).

On a side issue, nobody has suggested that you (iwfinger) purchase any new technology. But I'm sure you can understand that a working wireless connection is important in a laptop. I am not willing to move back to Windows and replacing the laptop isn't really an option either.

I have a further card coming (Atheros) but am willing to keep trying to get this Realtek working, if anyone has any suggestions?

Thanks for listening.

**Comment by lwfinger** [comment] 2016-12-02 20:11
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Closed by lwfinger** 2016-12-02 20:11 UTC
