### ISSUE TITLE
rtl8812ae: 5 Ghz doesn't works (AP Mode and Managed)

### ISSUE THREAD

**Issue by maxux** [lwfinger/rtlwifi_new#127] opened 2016-06-09 09:52 UTC
Hi,

When I want to put my rtl8812ae (`Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter (rev 01)`) card in AP mode, everything works in the 2.4 Ghz band, but nothing (no essid broadcasted at all) works in the 5 Ghz band.

In my hostapd.conf file, this options works:

```
hw_mode=g
channel=4
```

But this not (even when not using 802.11n, just 802.11a):

```
hw_mode=a
channel=48
```

I have no error in hostapd output:

```
Configuration file: /etc/hostapd/hostapd.conf
Using interface wlan0 with hwaddr 34:97:f6:XX:XX:XX and ssid "XXXX"
wlan0: interface state UNINITIALIZED->ENABLED
wlan0: AP-ENABLED 
```

And the output of `iw wlan0 info`:

```
Interface wlan0
    ifindex 5
    wdev 0x1
    addr 34:97:f6:XX:XX:XX
    ssid XXXXX
    type AP
    wiphy 0
    channel 48 (5240 MHz), width: 20 MHz (no HT), center1: 5240 MHz
```

I have no clue how to make 5 Ghz works in AP mode.

EDIT: after some test, it looks like that even in client mode, I cannot authentificate to a 5 Ghz existing AP. In 2.4 Ghz, all fine, in 5 Ghz:

```
Successfully initialized wpa_supplicant
wlan0: SME: Trying to authenticate with 10:0d:7f:XX:XX:XX (SSID='XXXXX-5G' freq=5240 MHz)
wlan0: SME: Trying to authenticate with 10:0d:7f:XX:XX:XX (SSID='XXXXX-5G' freq=5240 MHz)
wlan0: SME: Trying to authenticate with 10:0d:7f:XX:XX:XX (SSID='XXXXX-5G' freq=5240 MHz)
wlan0: SME: Trying to authenticate with 10:0d:7f:XX:XX:XX (SSID='XXXXX-5G' freq=5240 MHz)
wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="XXXXX-5G" auth_failures=1 duration=10 reason=CONN_FAILED
```

**Comment by BKPepe** [comment] 2016-06-26 10:07
I hope this will be enabled in future.. You can find it easily on ebay. It's very cheap.

**Comment by lwfinger** [comment] 2016-06-26 14:59
As far as I know, the 8821ae works in managed mode. If not, then it is your country code that is wrong. If so, then some diagnostic information would be a lot more helpful than this comment. In other words, it works for me. If it does not for you, then you need to help.

As for the AP mode, I am willing to test any suggested fixes.

**Comment by mcm** [comment] 2016-06-29 03:22
I can confirm this card works in AP mode on 5GHz with the driver in this repo. I'm still working on hopefully getting better speed out of it (I get about 130Mbps right now, even when connected on AC with a laptop I know is capable of faster), but it definitely works. Here's a hostapd.conf that works with it:

https://gist.github.com/mcm/7ff0639257b70fba3845ad6c66f1570e

Regulatory domain set to US:

```
alpine-wrt:~# cat /etc/modprobe.d/cfg80211.conf
options cfg80211 ieee80211_regdom=US
alpine-wrt:~# iw reg get
global
country US: DFS-FCC
	(2402 - 2472 @ 40), (N/A, 30), (N/A)
	(5170 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
	(5250 - 5330 @ 80), (N/A, 23), (0 ms), DFS, AUTO-BW
	(5490 - 5730 @ 160), (N/A, 23), (0 ms), DFS
	(5735 - 5835 @ 80), (N/A, 30), (N/A)
	(57240 - 63720 @ 2160), (N/A, 40), (N/A)

global
country US: DFS-FCC
	(2402 - 2472 @ 40), (N/A, 30), (N/A)
	(5170 - 5250 @ 80), (N/A, 23), (N/A), AUTO-BW
	(5250 - 5330 @ 80), (N/A, 23), (0 ms), DFS, AUTO-BW
	(5490 - 5730 @ 160), (N/A, 23), (0 ms), DFS
	(5735 - 5835 @ 80), (N/A, 30), (N/A)
	(57240 - 63720 @ 2160), (N/A, 40), (N/A)

alpine-wrt:~#
```

So its definitely not a driver problem

```
02:00.0 Network controller: Realtek Semiconductor Co., Ltd. RTL8812AE 802.11ac PCIe Wireless Network Adapter (rev 01)
	Subsystem: D-Link System Inc Device 3305
	Flags: bus master, fast devsel, latency 0, IRQ 27
	I/O ports at be00 [size=256]
	Memory at fd9fc000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: [40] Power Management version 3
	Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [70] Express Endpoint, MSI 00
	Capabilities: [100] Advanced Error Reporting
	Capabilities: [140] Device Serial Number 00-12-88-fe-ff-4c-e0-00
	Capabilities: [150] Latency Tolerance Reporting
	Capabilities: [158] L1 PM Substates
	Kernel driver in use: rtl8821ae
```

**Comment by lwfinger** [comment] 2016-12-02 20:03
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.

**Closed by lwfinger** 2016-12-02 20:03 UTC
